### ISSUE TITLE
Please make all text (e.g. "Cancel") customizable

### ISSUE THREAD

**Issue by HolgerSchulz** [HemantNegi/jquery.sumoselect#100]
To use sumoselect in other languages than English it would be great, if the hard coded text like "Cancel" would be customizable.

Thanks
     Holger

**Comment by mbosecke** [comment]
It's not documented but it looks like an appropriate setting was added: https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js#L38

**Comment by HemantNegi** [comment]
Yes that will do it

**Comment by HolgerSchulz** [comment]
Thanks!
