### ISSUE TITLE
How does one use # CSS IDs?

### ISSUE THREAD

**Issue by drtyrell969** [HemantNegi/jquery.sumoselect#102]
I have an application that has several SUMO lists on the page. How does one reference them via a CSS ID? I'm looking to do something like the following:

$('#myList').sumo.selectAll();

Is that possible?

**Comment by HemantNegi** [comment]
Yes you can do it by IDs also.
in your case 
`<select name="somename" id="myList">`
then use like
`$('#myList')[0].sumo.selectAll();`

**Comment by drtyrell969** [comment]
I'm getting the following error:

TypeError: undefined is not an object (evaluating '$('#myList')[0].sumo.selectAll)

My list has the option values, but the sumo plugin crashes. :(

**Comment by HemantNegi** [comment]
is the plugin initialized on that select element?
in console see the output of 
`$('#myList')`
`$('#myList')[0].sumo`

or can you setup a jsfiddle

**Comment by hinikunj** [comment]
@HemantNegi : my problem is with two select box.

`$('#sub_group_select').html(split_result[1]);
            $('#sub_group_select')[0].sumo.reload();//sumo reload
$('#facebookAuthDetail').html(split_result[4]);
                $('#fb_page_select')[0].sumo.reload();//sumo select`

First one reloaded well.
but second one throws an error called 👎  TypeError: $(...)[0].sumo is undefined.

Can you help me out what went wrong in my code. or reload function can be used once?

becuase $('.SlectBox')[0].sumo.reload();  Not working for both of them.

**Comment by pairmix** [comment]
same error for me

**Comment by sakoweb** [comment]
Worked for me.
window.mySelect = $('.SlectBox').SumoSelect();
window.mySelect.sumo.reload();
