### ISSUE TITLE
Bug: Searching, cannot enter spaces.

### ISSUE THREAD

**Issue by camway** [HemantNegi/jquery.sumoselect#103]
When typing in the search, spaces aren't allowed to be entered.

I was able to remedy this by commenting line 359 "case 32: // space" (according to github's line numbering).

I realize this probably isn't ideal, but I use enter for selecting anyway, so this wasn't a major issue for me.

**Comment by HemantNegi** [comment]
Oh, that's a major one

**Comment by HemantNegi** [comment]
Fixed now!

**Comment by camway** [comment]
This might be a bug on my end, but I'm getting a new error in about the same spot.
`Uncaught TypeError: e.target.is is not a function`

on line 354 jquery.sumoselect.js:
`if(e.target.is(O.ftxt))return; `

I was able to fix just by wrapping e.target in a jquery selector:
`if($(e.target).is(O.ftxt))return;`

**Comment by HemantNegi** [comment]
ok got it.
its beacuse `e.target` is not a jquery instance of element.

**Comment by camway** [comment]
Yep, wasn't a big deal, small update fixed it.  Ironically the error stopped the event chain anyway so the desired effect was still achieved lol.
