### ISSUE TITLE
SumoSelect does not display (.open on wrong element?)

### ISSUE THREAD

**Issue by izanev** [HemantNegi/jquery.sumoselect#105]
I've downloaded latest version from website (jquery.sumoselect - v2.1.0).

I applied to a multiple select. It works fine except....it doesn't show on click.

When I further investigate, it seems the plug-in puts "open" on inner HTML element "optWrapper". Plug-in CSS expects "open" to be on outer "SumoSelect" div.

Further info: it only happens on the minified js version in the package. When I replaced with the source js, it worked fine.

**Comment by steponavichus** [comment]
I faced with the same problem. Bug in minified version.

**Comment by HemantNegi** [comment]
Actually i am planning for a release soon, so not updating the min version.
Updated for now
