### ISSUE TITLE
Inject the options at the end of the body DOM to display on top of all other elements

### ISSUE THREAD

**Issue by mbosecke** [HemantNegi/jquery.sumoselect#106]
It'd be nice if the select options, when opened, had a minimal impact on the rest of the layout (i.e. not creating scroll bars or hiding behind other elements). I'm proposing that the markup for the options is appended to the end of the body element as opposed to being local to the original select element.

**Comment by HemantNegi** [comment]
similar issue. https://github.com/HemantNegi/jquery.sumoselect/issues/55
