### ISSUE TITLE
jquery.sumoselect.min.js doesn't work

### ISSUE THREAD

**Issue by firstinstance** [HemantNegi/jquery.sumoselect#108]
Hi Hemant,

the jquery.sumoselect**.min**.js doesn't work, jquery.sumoselect.js works fine.
You can test it in select_responsive.html and click on a mutli-select.

Thank you for your changes, i love your plugin. :-)

I still have a wish: Please select all if you click on "<label>Select All</label>" Thanks!!

Best wishes, Simon

**Comment by HemantNegi** [comment]
min version is outdated. you can minify by yourself  @ http://refresh-sf.com/
