### ISSUE TITLE
Support for 'change' event selection instead of index based

### ISSUE THREAD

**Issue by wubzz** [HemantNegi/jquery.sumoselect#115]
Hi,

First of great library! Trying to move over from select2 to this, but not being able to call `$('select').val(value).trigger('change')` is quite the turn off. Instead I would need to figure out the index of this dynamic value in the dropdown first, and then call `.sumo.selectItem(index)`;

Any chance to support this in the near future?

**Comment by HemantNegi** [comment]
Done
Now `.selectItem()` also accepts values.
so `.sumo.selectItem('some value')` is valid
