### ISSUE TITLE
Stop script Error

### ISSUE THREAD

**Issue by siva-UIDev** [HemantNegi/jquery.sumoselect#117]
Thanks for the plugin & really helped a lot(Nice UI). I am facing one issue here.When option items increases more than 1800,browser throwing stop script error...Can i get any help on this?

**Comment by HemantNegi** [comment]
Hi, 
can you provide more details like browser info, or even better if you can setup a fiddle replicating the issue.
Thanks

**Comment by siva-UIDev** [comment]
Hi,

Will provide a complete info in github & will try for fiddle set up...

**Comment by HemantNegi** [comment]
Please reopen if you face this again!
