### ISSUE TITLE
toggSel() doesn't toggle if search criteria is string based

### ISSUE THREAD

**Issue by rusticnerd** [HemantNegi/jquery.sumoselect#119]
Index/number based toggling works, though.

**Comment by HemantNegi** [comment]
Its not a public function. however if you want to use it, this is how you do it.
to select : `.toggSel(true, 'value');` 
to unselect : `.toggSel(false, 'value');`

**Comment by rusticnerd** [comment]
Oh hey, I'm sorry, I should have been clearer.  When toggSel() is called via.. for example:

  $('select.SlectBox')[0].sumo.selectItem('volo');

...the string value gets passed into .toggSel().  The logic for integer-based arguments works, but string-based logic is bad.  Line 554 has:

                        if(!O.mob)O.optDiv.find('ul.options li.opt').eq(i).toggleClass('selected',c);
The ".eq(i)" is assuming the argument is integer, but when its a string value, the checkbox never gets checked.

I'd supply a patch, but I'm not a very good javascript programmer and so I leave it to the expert!  Your kit is very nice, btw!

**Comment by HemantNegi** [comment]
OH,
Thats a bug.

Thanks.
