### ISSUE TITLE
Clear all items

### ISSUE THREAD

**Issue by csotelo8885** [HemantNegi/jquery.sumoselect#12]
Hi, how clear/uncheck all items?

**Comment by mrhirenmodi** [comment]
Hi, I have used this sumoselect library for the dropdown below but I am not able to write jquery function to reset the previously selected value. Could you please help me?
			<div class="list-group-item">
				<span class="form-group"><b><strong> Agency Name
							: </strong></b></span> &nbsp;&nbsp;&nbsp;&nbsp; <select multiple="multiple"
					placeholder="-- Agency Name --" id="crruploadselection"
					class="form-group selAll">
					<option value="Education">Education</option>
					<option value="Defence">Defence</option>
					<option value="Planning">Planning</option>
					<option value="Water">Water</option>
				</select>			
			</div>

**Comment by mrhirenmodi** [comment]
<div class="list-group-item">
				<span class="form-group"><b><strong> Agency Name
							: </strong></b></span> &nbsp;&nbsp;&nbsp;&nbsp; <select multiple="multiple"
					placeholder="-- Agency Name --" id="crruploadselection"
					class="form-group selAll">
					<option value="Education">Education</option>
					<option value="Defence">Defence</option>
					<option value="Planning">Planning</option>
					<option value="Water">Water</option>
				</select> <br>
				<br>
				<button type="button" id="crrUpload"
					class="ui-button-primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
					role="button">
					<span class="ui-button-text">Submit</span>
				</button>
			</div>
