### ISSUE TITLE
floating menu body scrolling query

### ISSUE THREAD

**Issue by tjl666** [HemantNegi/jquery.sumoselect#121]
Excellent plugin, just one small query - when viewing on my iphone 6, when the dropdown swaps to a floating panel, when I try to scroll up or down the menu panel (when it is longer than the view port), it on and off scrolls the body/website beneath rather than the actual floating menu panel itself. Is there any way that when a floating menu panel is visible, that the site beneath is non scrollable? Many thanks :)

**Comment by PixelZombie** [comment]
I had the same issue and it seems thats due to the absolute positioning of MultiControls (OK / Cancel). I added the following css in order to make the options scollable. Maybe this works for you too

```
.SumoSelect > .optWrapper.isFloating > .options {
    max-height: 100%;
    box-shadow: 0 0 100px #595959;
    padding-bottom: 33px; // <---- Add this line
}
```
