### ISSUE TITLE
Fade in dropdown

### ISSUE THREAD

**Issue by tjl666** [HemantNegi/jquery.sumoselect#122]
This is not an issue, just a question.  Is there a specific reason why you have removed the fade in style of the dropdowns on the latest version?  From what I can see, It seems it's just CSS updates where you have replaced visibility/opacity/animation settings with basic display:none/block.

I've changed these back to visibility/opacity/animation as I like the fade-in style, but I just wanted to check that this won't cause any issues and that you hadn't removed it for some cross browser/device functionality or behaviour reason?

Many thanks!

**Comment by HemantNegi** [comment]
The main reason was, we can not set the `display:none` while maintaining the transition in `opacity`.
and it was occupying hidden space below the select which may disturb the page height(scrolbar) when placed at very bottom of the page.

However if you are not placing it at bottom of the page its perfectly fine
