### ISSUE TITLE
No matches for "Monkey" add new

### ISSUE THREAD

**Issue by cakama3a** [HemantNegi/jquery.sumoselect#123]
How about something like this? http://prntscr.com/az0579

**Comment by HemantNegi** [comment]
That is a very specific use case.
However i think you can use some tricks in existing plugin to achieve the same.

you can put some custom html in `noMatch:` and then bind some events on it and use the sumoselect apis to manipulate list items.

**Comment by cakama3a** [comment]
I make it like this

`$('.SlectBoxSearchAdd').SumoSelect({
	search: true,
	noMatch: 'No matches for "{0}" <a class="newSumo">Add new</a>'
});
`

and then

`$('.SumoSelect').on('click', '.newSumo', function(){
	newopt = $(this).parents(".SumoSelect").find('.search-txt').val();
	var sumoFind = $(this).parents(".SumoSelect").find("select");

	sumoFind[0].sumo.add(newopt);

	sumoFind[0].sumo.unSelectAll();

	sumoFind[0].sumo.selectItem(newopt);

	sumoFind[0].sumo.reload();
});
`

This works fine

**Comment by HemantNegi** [comment]
Awesome :100:
