### ISSUE TITLE
Mobile issues

### ISSUE THREAD

**Issue by tjl666** [HemantNegi/jquery.sumoselect#124]
Hey Hemant,

Thank you for the updates, sadly still having the same issues my end 
- When the floating menu is shown on mobile when scrolling within it, it scrolls the page beneath instead.
- Sometimes the position of the floating menu is actually right down the page, and not within view, so unless you scroll right down, you would think it wasn't working, as nothing seems to happen.

I then changed it so that on mobile it didn't show this customised dropdown, and in turn allowed it to use the default mobile ui.  But this is where, when you have the form to auto-submit, it doesn't give you chance to select an option, as the first option is by default selected and you are taken to the results page.

My solution...

I got it to use the forceCustomRendering: true again with floatWidth: 50, then what it does is it uses the custom style but without the floating aspect which is currently experiencing the positioning / scrolling issues and this then all works well for me.

I just wanted to let you know though as I think as part of your recent updates you had fixed the mobile floating menu scroll problems, but sadly for me there is no change.

Many thanks again for a great plugin either way, as even with the work around above, it works and looks great!

**Comment by HemantNegi** [comment]
Thanks for your comments, Actually i don't have an iphone at the moment so i cant test it thoroughly.
just want you to check when full screen popup opens, a class `sumoStopScroll` is added to the body you can try playing with styles in that class to stop background scrolling.
