### ISSUE TITLE
Feature Request: Tool tip like list of selected items

### ISSUE THREAD

**Issue by camway** [HemantNegi/jquery.sumoselect#128]
We are trying to find a way to be able to show which items have been selected. There is a way to do it currently, but depending on the size of the SumoSelect and the length of the items involved we only see 2-3 items.  I was thinking about adding an option for some kind of tool tip that on hover (or some other event) would enumerate every item which has been selected.

If we really wanted to flush it out, you could have options for it to be enabled at all, max items to display, maybe a line break between items (I'm spit balling).

Is this something anyone else would find use for? I'm okay with just rigging it on my version if needed, but just in case it could be used by anyone else I figured I would share.

**Comment by HemantNegi** [comment]
you can now add a title attribute to your options.
