### ISSUE TITLE
IE8 - two problem

### ISSUE THREAD

**Issue by husky83** [HemantNegi/jquery.sumoselect#13]
I have two problem in IE8. 
First is in line 306 - i was add 'toString()' before 'toLowerCase()' and now it's work.
second problem is in 'get' and 'set' - ie8 doesn't support getters and setters. I working on it.

**Comment by HemantNegi** [comment]
Fixed in new version!!

**Comment by wild-north** [comment]
>>> second problem is in 'get' and 'set' - ie8 doesn't support getters and setters.
the problem still here
http://prntscr.com/6lk0av
