### ISSUE TITLE
Could you publish it on npmjs.org?

### ISSUE THREAD

**Issue by wbotelhos** [HemantNegi/jquery.sumoselect#134]
Please? (:

**Comment by malde** [comment]
If I'm not mistaken, anyone could do that, since it's under MIT license, right?

**Comment by HemantNegi** [comment]
I am not much familiar with publishing on npmjs.
Yes any one can do that.
Just send me a Pull Request with the desired changes and i will merge them.

**Comment by wbotelhos** [comment]
Anyone can, but is cool it be on your account, since you are the owner. Your Merit! (:

You can just follow this, it is easy: https://docs.npmjs.com/getting-started/publishing-npm-packages

I saw you already created the `package.json`, so... almost done! (;

**Comment by abhishekdev** [comment]
This package was published to npm a year back, however there seems to be a version issue now.

The version published on npm is `v3.0.3`, which was *never* released (post probably published from master branch at that time). I stumbled upon this when I received an undefined variable error in strict mode. The issue has already been fixed on master but the package from npm (which is also at v3.0.3) does not have the fixes

@jeremykenedy: Could you please update the package on npm?

**Comment by jeremykenedy** [comment]
@abhishekdev updated

**Comment by Zenoo** [comment]
@jeremykenedy Could you delete the package on npm please?  
I have a script ready that will publish on npm after every new release.

**Comment by jeremykenedy** [comment]
As soon as I get time I will. When it created a few years ago there was the need but seems like you are all caught up now. Thanks for the package!

**Comment by jeremykenedy** [comment]
You a have been added as a maintainer on npmjs.

I didn’t think it was a good idea to delete the package since it does reference your codebase as well as peoples projects are dependent on it and its getting 500+ downloads a week.

**Comment by Zenoo** [comment]
Thanks !
