### ISSUE TITLE
IE 11 listbox is undefined 

### ISSUE THREAD

**Issue by jdeskin** [HemantNegi/jquery.sumoselect#135]
I am running an asp:listbox and it is working in google chrome and in firefox but when i try it out in IE 11 i am getting this javascript error and the control is poping up like a normal listbox would. Am i doing something wrong? 

![image](https://cloud.githubusercontent.com/assets/19846445/15947172/d3a44d4c-2e5f-11e6-86e1-21b9c72ab047.png)

![image](https://cloud.githubusercontent.com/assets/19846445/15947179/d96d39fa-2e5f-11e6-9a75-b961efa35b8d.png)

**Comment by HemantNegi** [comment]
You are initializing it the wrong way.
its a invalif query selector.

```
$('#lbSaleStatus').SumoSlect();
```
