### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by jaimeadvantageousmediapartners** [HemantNegi/jquery.sumoselect#136]
Is there a way to alphabetize the ul:options (select tag dropdown list), or must they be random?
![photo gallery tag sort issue](https://cloud.githubusercontent.com/assets/18216421/15948246/af2f8c16-2e6d-11e6-9466-0ef28f324a55.JPG)

**Comment by HemantNegi** [comment]
No,
You have to put them in alphabetic manner inside the select.
