### ISSUE TITLE
why select all option in sumo select not visible in mobile device.

### ISSUE THREAD

**Issue by srijoy** [HemantNegi/jquery.sumoselect#140]
Hello Hemant,
we are using Sumo Select drop down for our mobile application demo.We want to incorporate select all option in mobile devices.But it is not visible as said.We want to customize the code.But before that want to know the reason why select all is not visible in mobile device , so that our customization will be easy.
Regards,

**Comment by HemantNegi** [comment]
Native select popup is displayed on mobile devices.
however if you want to force desktop style rendering in mobiles then set 
```
forceCustomRendering: true
```

**Comment by dev-vkagrawal** [comment]
Hi @HemantNegi  Select All option is not visible in Android Firforx, Chrome browsers. Any fix for this?
Thanks
