### ISSUE TITLE
Facing a very strange issue with sumoselect.

### ISSUE THREAD

**Issue by phpvikas** [HemantNegi/jquery.sumoselect#141]
Hello Hement,

I am facing a new issue with sumoselect. I am using this plugin for filtration purpose and sometime it select some items automatically, suppose i select option 1 and it select option 2 or 3 or any other option randomly. it is not happening every time but I am facing this every 3rd or 4th attempt.

Please see the following gif image for reference..

![first](https://cloud.githubusercontent.com/assets/13044509/16335740/ec72fefa-3a25-11e6-89b4-13fa84cee47c.gif)
![second](https://cloud.githubusercontent.com/assets/13044509/16335762/08eb5730-3a26-11e6-98ea-5736ac93fcdc.gif)

**Comment by HemantNegi** [comment]
I am not getting this, No one else reported this till now.
Can you set up a fiddle replicating this issue.

Closing this for now.

**Comment by oldusername91** [comment]
Hi phpvikas,

The native select element (the one you apply .SumoSelect() to) is set to have an opacity of 100%. So sometimes when clicking off you are actually still interacting with the native select.

Using developer tools, inspect the sumo select, go to its inner <select> and apply an extra css rule, opacity = 1.

I solved the problem by using a z-index rule on the native select so you can no longer interact with it.
