### ISSUE TITLE
I have a chain of categories. I select a category from a select box, it shows its subcategories in the other dropdown selection box. But after applying sumoselect It doesn't refresh/change after a ajax call.

### ISSUE THREAD

**Issue by omprakashroy12** [HemantNegi/jquery.sumoselect#146]
listsub = "1,2,3";
var y=0;
var splitcat = listsub.split(",");
for(x=0;x<splitcat.length;x++){
    y++;
    $('.subcategorySelect')[0].sumo.add(splitdata[x],y);
}
It appends data but doesn't remove the options from first time populated options.

**Comment by HemantNegi** [comment]
To remove old data. you have to delete the options in actual select element.
You can always reload sumoselect by
` $('select.SlectBox')[0].sumo.reload();`
