### ISSUE TITLE
ie11 UI bug if search is enabled

### ISSUE THREAD

**Issue by spanevin** [HemantNegi/jquery.sumoselect#149]
create a sumoselect control with lots of options (>200) with search=true
enter some non-existing label into search box

Expected: "No matches found for "<your text>" box appeared.

Actual (IE11, maybe older IE): very big empty box (longer than page height) appears, no text at all.

FF/Chrome works fine.

**Comment by YUDIANYINGZI** [comment]
I also encountered this problem
My solution is as follows
1.
O.ftxt.on('keyup.sumo',function(){
var hid = O.optDiv.find('ul.options li.opt').each(function(ix,e){
	e = $(e);
	if(e.text().toLowerCase().indexOf(O.ftxt.val().toLowerCase()) > -1)
		e.removeClass('hidden');
	else
		e.addClass('hidden');
}).not('.hidden');
**!hid.length ? O.ul.hide() : O.ul.show();**
P.html(settings.noMatch.replace(/\{0\}/g, O.ftxt.val())).toggle(!hid.length);

2.
O.CaptionCont.click(function (evt) {
	O.E.trigger('click');
	**O.ul.show();**
	if (O.is_opened) O.hideOpts(); else O.showOpts();
	evt.stopPropagation();
});

**Comment by HemantNegi** [comment]
Right now i can not test this on IE11.
Any help will be appreciated.

**Comment by Zenoo** [comment]
Can't reproduce the bug anymore, it must have been fixed somewhere down the line.  
Feel free to reopen this issue if you still encounter this bug.
