### ISSUE TITLE
Callbacks and validation

### ISSUE THREAD

**Issue by shivekundefined** [HemantNegi/jquery.sumoselect#153]
Is there any callback function when "Okay" or "Cancel" was clicked?
Is there any way to validate on okay that no item was selected or alert on maximum number selection.

**Comment by HemantNegi** [comment]
Currently there is no callback function on ok/cancel.
The change event is triggered only when selection changes in mutiselect.
However you can hookup your custom function at https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js#L189
