### ISSUE TITLE
to send said to be selected, but is not

### ISSUE THREAD

**Issue by eduardodallmann** [HemantNegi/jquery.sumoselect#155]
in link jsfiddle:
select any option from the first select, it will unlock the second select and create your options.

without selecting anything in the second select, click submit.

the message will inform that is option selected in the second select. why?

https://jsfiddle.net/eduardodallmann/4q3qw6ee/5/

**Comment by HemantNegi** [comment]
its the default behavior of the native select element. when you inset an option in an empty select it gets selected.
I think to overcome this problem you have to manually select an empty element in select.
you can use `.selectitem()` api for that.
