### ISSUE TITLE
Place holder for single select

### ISSUE THREAD

**Issue by hanwiz** [HemantNegi/jquery.sumoselect#158]
Can we use the following HTML with CSS? What's the catch on this implementation?

`<option selected disabled value="">Placeholder</option>`
.SumoSelect > .optWrapper > .options li.opt.disabled {
  display: none;
}

**Comment by hanwiz** [comment]
Ok, we can add a class placeholder the first option to remove the disabled side-effect.

```
<option selected class='placeholder' value="">Placeholder</option>
.SumoSelect > .optWrapper > .options li.opt.placeholder {
display: none;
}
```

**Comment by Grawl** [comment]
it's a workaround

**Comment by ARRON-LAI** [comment]
Does it work on firefox ?  I tried this method, it works fine on chrome but on ff it still make my first option as selected and cannot show my placeholder

**Comment by DSergioD** [comment]
$('.SumoSelect').each(function () {
             var $this = $(this);
             $this.find('> .optWrapper.multiple .options li.opt').on('click', function () {
                 $('.form-meeting .SumoSelect > .optWrapper.multiple > .options li.opt').removeClass('selected');
                 $(this).addClass('selected');
                 var $labelText = $(this).find('label').text();
                 $this.find('.CaptionCont').attr('title', $labelText);
                 $this.find('.CaptionCont > span').text($labelText);
             });
         });
