### ISSUE TITLE
Keep highlighted selection

### ISSUE THREAD

**Issue by eduardodallmann** [HemantNegi/jquery.sumoselect#161]
In some situations in my site, the same name option can be found in different optgroup (although they have different value).

How to keep the highlighted choice?

![image](https://cloud.githubusercontent.com/assets/7562936/20029518/45cee338-a335-11e6-8920-db6b8ce05a28.png)

Thanks!

**Comment by HemantNegi** [comment]
Can you provide a js fiddle for that.

**Comment by eduardodallmann** [comment]
https://jsfiddle.net/eduardodallmann/c74rmcwa/2/

Remembering that is not a problem. I'm giving you a suggestion for improvement.

Suggestion: Keep the selection highlighted. To identify the choice if there are more than one item with the same name.

**Comment by HemantNegi** [comment]
Please updated to the latest version.
Selection will be highlighted when you start pressing the arrow down/up keys. 

if you want it to be always selected you can use below css.
`.SumoSelect > .optWrapper > .options  li.opt.selected {background-color:blue;}`
