### ISSUE TITLE
multi select displays both native and custom controls

### ISSUE THREAD

**Issue by mcvrana** [HemantNegi/jquery.sumoselect#162]
We have multi select dropdowns that on the iphone and ipad displays both the native and sumoselect  controls.  Has anyone else had this issue?

the sumo select options are:

sumoMultiArgs = 
  csvDispCount: 2
  selectAll: true
  locale: ['OK', 'Cancel', 'All']
  placeholder: 'Choose...'
  captionFormatAllSelected: 'All',
  nativeOnDevice: ['Android', 'BlackBerry', 'Opera Mini', 'IEMobile', 'Silk'],
  forceCustomRendering: true,

thanks.

**Comment by HemantNegi** [comment]
That is weird, never happened before. 
Try removing nativeOnDevice option. or set it to empty array

**Comment by HemantNegi** [comment]
I am assuming this is not happening again.
