### ISSUE TITLE
Ability to customize 'all selected!' text

### ISSUE THREAD

**Issue by mip1983** [HemantNegi/jquery.sumoselect#163]
If you use the 'selectAll: true' option, and select all, you'll see some text like:

> 5 all selected!

Is there a way (or can it be added as an option) so this text can be customized or localized? The 'captionFormat' option only works when you haven't selected all.

**Comment by mip1983** [comment]
I realize this is an option 'captionFormatAllSelected' as I've seen it in the source, it's just not documented here:

http://hemantnegi.github.io/jquery.sumoselect/

**Comment by HemantNegi** [comment]
Updated Docs!

Thanks.
