### ISSUE TITLE
Sumoselect with Ok/Cancel buttons remember selected values after click away

### ISSUE THREAD

**Issue by amarsalunke** [HemantNegi/jquery.sumoselect#164]
$('.btnOk').on('click', function () {

            debugger;
            var obj = [],
        items = '';
            $('.testSelAll option:selected').each(function (i) {
                obj.push($(this).val());
                $('.testSelAll')[0].sumo.unSelectItem(i);
            });
            for (var i = 0; i < obj.length; i++) {
                items += ' ' + obj[i]
            };
            alert(items);
        });

after click ok button all selected item Clear

**Comment by HemantNegi** [comment]
Can you setup a jsfiddle for this issue.

Please reopen once done.
