### ISSUE TITLE
How to get the value of option when it's un selected?

### ISSUE THREAD

**Issue by safooraMA** [HemantNegi/jquery.sumoselect#166]
Hi Hemant,

    Thanks a lot for such a great plugin. I am able to get the value of checkbox option when it's selected. Can  you please suggest me how can i get the value of same option when it is unseleced?

**Comment by HemantNegi** [comment]
You can hook up a function to change event of select and get the value of select at that point.
but if you want to get unselected value in a simple select then you can not do that, for that you have to store the previous value in some variable.
for multi select follow this link http://stackoverflow.com/questions/35093122/get-unselected-option-from-multiple-select-list

**Comment by safooraMA** [comment]
Hello Hemanth,

    Thank you so much for your response. It helped me.

With Regards,
Safoora M.A

**Comment by tpaksu** [comment]
For those who still need a solution for this:

On initialization:
```
$("select[multiple]").each(function(){
    $(this).data("selected", ($(this).val() || []).join(";"));
});
```

Then add the event
```
$("select[multiple]").on("change", function(e) {
  var prevSelected = $(this).data("selected") ? $(this).data("selected").split(";") : [];
  var currSelected = $(this).val() || [];
  var deselected = prevSelected.filter(function(s) {
    return currSelected.indexOf(s) == -1;
  });
  var selected = currSelected.filter(function(d) {
    return prevSelected.indexOf(d) == -1;
  });

  if (selected.length > 0) {
    var $this = $(this).find("option[value='" + selected[0] + "']").first();
    console.log("selected", selected[0], $this);
    // your code here runs when an item is selected
  } else if (deselected.length > 0) {
    var $this = $(this).find("option[value='" + selected[0] + "']").first();
    console.log("deselected", deselected[0], $this);
    // your code here runs when an item is unselected
  }
  // don't forget to store new state
  $(this).data("selected", ($(this).val() || []).join(";"));
});

```
