### ISSUE TITLE
selectItem returns from loop

### ISSUE THREAD

**Issue by Yamin-lawar** [HemantNegi/jquery.sumoselect#169]
I am facing a strange behaviour while selecting multiple items in loop.
So, when I try
for(i=0; i<2; i++) {
   $('select#salaryBand')[0].sumo.selectItem(i).index());
}

it selects only 1 item, and then returns;

**Comment by HemantNegi** [comment]
It should work
the `selectItem(i)` method does not return anything.

```
for(i=0; i<2; i++) {
$('select#salaryBand')[0].sumo.selectItem(i);
}
```
