### ISSUE TITLE
Add methods selectByIndex and selectByValue

### ISSUE THREAD

**Issue by BenjaminCanape** [HemantNegi/jquery.sumoselect#170]
I am facing a problem with the selectItem(index/value) method.

I need to pre-select one or more options by values, but my values are numbers.
So what is happening is when i do that $('select')[0].sumo.selectItem(5); it pre-select the option of index 5 not the option of value 5. 
Is there a way to do that ? (I am going to do it in pure js, for now, but it would be great to do it directly)
If not, is there a way you could add a selectItemByValue(value) method ?

**Comment by HemantNegi** [comment]
`selectItem()` takes an index or value of item to be selected.
indexes are integer
values are string

so select by value will be `$('select')[0].sumo.selectItem("5");`
