### ISSUE TITLE
Feature request onOpen and onChange events

### ISSUE THREAD

**Issue by ahait** [HemantNegi/jquery.sumoselect#171]
To add 2 functions as one of the parameters, like for example:
onOpen: function(instance, checkedItems) { }
onChange: function(instance, checkedItems) { }

That will be triggered when one clicks on the element (to see the list) or when one actually clicks on one of the checkboxes/dropdown.

**Comment by HemantNegi** [comment]
Added :https://github.com/HemantNegi/jquery.sumoselect/commit/19f1e008975cb92155c1cc2b9729afc2bd263316

eg.
`
$('select.SelectBox').on('sumo:opened', function(sumo) {
   // Do stuff here
   console.log("Drop down opened", sumo)
});`

For change you can always bind to underlying select element.
`$('select.SelectBox').on('change', function(){
   // selection changed
})`

**Comment by Bill-VA** [comment]
Better yet, an event that would fire upon closure _**if**_ changed.  The solution above does indeed capture changes, but fires every time an option is selected or deselected.

**Comment by Bill-VA** [comment]
I think I might have solved my own issue:
`$('#myselect').SumoSelect({ 
		okCancelInMulti: true, 
		selectAll: true
	});
	var myselect_changed = false;
	$('#myselect').on('sumo:closed', function(sumo) {
		if(myselect_changed){myfunction(); myselect_changed = false;}
	});	
	$('#myselect').on('change', function(){
   		myselect_changed = true;
	})`

**Comment by ETP-ShowPortal** [comment]
Bill-VA you just saved me a headache thanks!
