### ISSUE TITLE
dynamic search is not working on mobile view

### ISSUE THREAD

**Issue by arleybequadro** [HemantNegi/jquery.sumoselect#172]
Hello!
We're using sumoselect and we've just found out that search is not working on mobile view. We made a select that expects at least 3 characters or an asterisk before go to the server and get some data to show. I have read #133 and also the demo page to found out that I need to use:

  _okCancelMulti: true, 
  triggerChangeCombined: true,
  forceCustomRendering: true,_

After these lines the behavior changed and now it's poping-up the search field and letting me type, but the result is not rendering so well. It shows a very thin line above the select. I believe that is the result with height= 1 pixel; 

 My code is something like:

_$(ddlId).SumoSelect({
		okCancelMulti: true, 
		triggerChangeCombined: true,
		forceCustomRendering: true,
                search: true,
                searchText: "Pesquisar (3 caracteres ou mais)",
                placeholder: "Pesquisar",
                triggerChangeCombined: true,
                //captionFormat: url
    }); //pt-br_

Please let me know of any solution towards that. Thanks in advance.

**Comment by HemantNegi** [comment]
You can check css and patch it according to your needs.
Also i have made some changes to css recently, so please try using the updated code from repo.

Reopen this if not solved.
