### ISSUE TITLE
SelectAll option true crashes sumoselect in Single item mode

### ISSUE THREAD

**Issue by SamuelYvon** [HemantNegi/jquery.sumoselect#174]
Version : v3.0.2

What I expected : When I start the sumo select in single item mode, and the select all option is activated, the select simply ignores the "single item mode"

What happens : It crashes and it never completes the initialization
Stacktrace:
![image](https://cloud.githubusercontent.com/assets/12652003/22627364/d91bfdd6-eb8f-11e6-8022-48300126b066.png)

The SelectAll option is irrelevant in a single select mode. Since I often switch my select from single to multiple, leaving the select all option was convenient. I found a fix, and will do a pull request later.

**Comment by HemantNegi** [comment]
Thanks for pointing out
