### ISSUE TITLE
Add Sumoselect on dynamic created select list.

### ISSUE THREAD

**Issue by ArchimidisM** [HemantNegi/jquery.sumoselect#178]
Dear all, I am trying to create a select list, by creating and populating it dynamically.
However when I try to add the sumoSelect it does not enable it. Only when I re run the script,the second time the multicheckbox is properly rendered.

How can I apply the sumoselect on a dynamically created select list?

**Comment by HemantNegi** [comment]
Initialize sumoselect after your list is completely populated.
or 
you can use `reload()` method
`$('select.SlectBox')[0].sumo.reload();`
