### ISSUE TITLE
Keyboard access to OK and Cancel buttons in Multiselect

### ISSUE THREAD

**Issue by palsi** [HemantNegi/jquery.sumoselect#179]
Hi Hemant, 
Issue #121 says tab key selection and keyboard navigation is already there but I have not be able to navigate to OK and the Cancel buttons in the dropdown using keyboard? Can you please let me know the keyboard access keys please?
or 
If that is not there currently how can we achieve it? To set tab index for the OK and Cancel buttons so that they can be accessed using keyboard only when there is no mouse.

Thank you so much,
Pallavi

**Comment by HemantNegi** [comment]
Please use the latest version from repo.

**Comment by palsi** [comment]
That worked like a charm!!!!!! THANK YOU!!!!

**Comment by palsi** [comment]
Hi Hemant, Can we please add ctrl+A and ctrl+D keyboard access to select/deselect all items in the dropdown or any other keyboard access to the same effect please? This is only last thing pending for our 508 compliance.
Thank you so much again! 
Pallavi

**Comment by HemantNegi** [comment]
For now added keyboard shortcuts for select/unselect all.
select all :  ctrl + a
unselect all: ctrl + shift + a
