### ISSUE TITLE
A setup parameter to have "click away" choose OK instead of Cancel

### ISSUE THREAD

**Issue by Reelix** [HemantNegi/jquery.sumoselect#181]
If you have multi-select enabled with the OK / Cancel buttons, choose an item, then click away, it clicks "Cancel" by default which deselects the recently chosen item.
  
A good setup parameter would be that it clicks "OK" instead of "Cancel" 
  
Thanks for the great control, and enjoy the rest of your day! :)

**Comment by HemantNegi** [comment]
Yes, i was in a dilemma when deciding that.
I think it could be ones personal preference. 

So let us give it some time and see what other people want it to be.

Thanks

**Comment by ahait** [comment]
I agree with reelix. I think it should be "OK".

**Comment by eommund** [comment]
I agree too, click-away should be "OK", or at least configurable.

Otherwise - awesome control, well done!

**Comment by StefanHumberg** [comment]
Hi, i'm on jquery.sumoselect - v3.0.3 with jquery-3.2.1.min.js in Chrome 56.0.2924.87 / IE 11.
I see a slightly different behaviour: When i select multiple items and click away, the first item remains selected, but the others get lost...

I would love to see a setup parameter to influence "click away" and i.m.h.o. it shoud either be "click away" == cancel (and unselect selected items) or "click away" == select marked items.

Thanks a lot ! (This is the best plugin i found so far for multiselect-dropdowns, awesome !)

**Comment by HemantNegi** [comment]
Thanks for your inputs.
Added a setting for that `isClickAwayOk`
although default behavior is still cancel.

**Comment by AbdulShaikh** [comment]
@HemantNegi: Have you removed isClickAwayOk settitng? can see it on v3.0.2 release
