### ISSUE TITLE
Need a maxMultiSelectOptions param so you can only select X options in a multi select

### ISSUE THREAD

**Issue by hickerm** [HemantNegi/jquery.sumoselect#183]
If you have a multi-select, you should be able to configure some sort of **maxMultiSelectOptions** param in the config object like so:

    $('.multiple-select').SumoSelect({
        placeholder: 'Select up to 3 items',

        maxMultiSelectOptions: 3
        maxMultiSelectOptionsSelected: 'Maximum {0} items selected'
    });

In the case above, you would only be able to select 3 options from the multi select. Upon selecting the 3rd option, all other options should become disabled.  If you then deselect an option (from having the max 3 selected), then those disabled options become enabled.

An appropriate message string should be presented as well as another config param, **maxMultiSelectOptionsSelected**  which would simply output "**Maximum 3 items selected**" in this example.

**Comment by HemantNegi** [comment]
I think this kind of validations can be handled separately, outside the plugin.
Better keep it that way

**Comment by JoeriAben** [comment]
Would be nice if there was a `maxSelect` option indeed. I agree with @HemantNegi that you need to check it on server side as a part of the validation. But it would be great for the user experience if the plugin could do it as well. So hopefully someone does a pull request for this.
