### ISSUE TITLE
Select All-checkbox is not working as expected when combining multiple + selectAll + search-field 

### ISSUE THREAD

**Issue by eommund** [HemantNegi/jquery.sumoselect#184]
Combining multiple + selectAll + search-field gives unwanted behaviour when all items in a search result is selected. The selectAll-checkbox is then checked, but when you reopen the dropdown - the selectAll-checkbox is still checked (even though not all items are checked. 

An example:
![image](https://cloud.githubusercontent.com/assets/18329551/23847517/0609fd20-07d3-11e7-8e3c-428dfa7da894.png)

Searching for "o":
![image](https://cloud.githubusercontent.com/assets/18329551/23847536/1ece3a06-07d3-11e7-97b0-d8675d526a00.png)

Selecting "Porche", notice the selectAll is automatically checked:
![image](https://cloud.githubusercontent.com/assets/18329551/23847555/3dccc81e-07d3-11e7-9258-1e82d533326c.png)

Closing the dropdown:
![image](https://cloud.githubusercontent.com/assets/18329551/23847570/509736dc-07d3-11e7-9f99-d3788964e98b.png)

Reopening the dropdown. Notice that the selectAll-checkbox is still checked, even though only three items are checked:
![image](https://cloud.githubusercontent.com/assets/18329551/23847607/79038eb8-07d3-11e7-89fc-93a9cfa79ab3.png)

**Comment by HemantNegi** [comment]
Thanks for pointing out.
Fixed now, please verify.
