### ISSUE TITLE
Feature request - On "Select All" - run onChange once

### ISSUE THREAD

**Issue by eommund** [HemantNegi/jquery.sumoselect#185]
When a user selects "Select All" button on a multiple list, an onChange event is fired for each element that has changed. 

If I have 100 unchecked items in my dropdown and click "Select All", 100 onChange events are fired.

Would it be possible to make this a single onChange event?

Thank you for your time! :)

**Comment by HemantNegi** [comment]
There is an option for this:
`okCancelInMulti: true`
`triggerChangeCombined : true`

This trigger the chage event only once

**Comment by eommund** [comment]
But no option if we do not want the OkCancel-buttons?
