### ISSUE TITLE
DE-SELECT all selected option added

### ISSUE THREAD

**Issue by Rah1x** [HemantNegi/jquery.sumoselect#187]
Hi,

I needed a **DE-SELECT** option so ive created one. Im posting it here so if any body needs it.

**Scenario:**
List has many many options, is preselected with a few of them. So who has the time to `scroll down like 100s of them` to uncheck the ones checked previously!  Furthermore, The SelectAll option on the other hand takes 2 clicks to deselect instead of 1, and its too slow (I guess someone mentioned that it fires event for each checkbox).

So here is the code, ive placed select tag inside a span with id `par_sumo`. Also the sumo is initialised using `selectAll: true`:
```
$('#par_sumo .SumoSelect .SelectBox').click(function(){
if($(this).parent().hasClass('open')){
$.desel_sumo_multi('#par_sumo', ($(this).attr('title')==''));
}
});


/** DESELECT SUMO **/
$.desel_sumo_multi = function(id, is_empty)
{
    if(is_empty)
    {
        $(id+' .select-all').hide();
        return false;
    }

    $(id+' .select-all').addClass('selected').removeClass('partial');

    $(id+' .select-all label').html('De-Select All');

    $(id+' .select-all.selected > label').css('color', '#EA5745');
    $(id+' .select-all.selected > span i').css('background-color', '#EA5745');

    $(id+' .select-all').click(function(){
    $(this).parent().siblings('.SelectBox').find('span').remove();
    $(this).hide();
    //$(id+' .btnOk').click(); //auto click Ok button if needed
    });
};

```

**Comment by HemantNegi** [comment]
Created a wiki for this.
https://github.com/HemantNegi/jquery.sumoselect/wiki/DE-SELECT-all-selected-option-added

**Comment by mrhirenmodi** [comment]
Hi, I have used this sumoselect library for the dropdown below but I am not able to write jquery function to reset the previously selected value. Could you please help me?

**Comment by mrhirenmodi** [comment]
<select multiple="multiple"
					placeholder="-- Agency Name --" id="crruploadselection"
					class="form-group selAll">
					<option value="Education">Education</option>
					<option value="Defence">Defence</option>
					<option value="Planning">Planning</option>
					<option value="Water">Water</option>
				</select>

**Comment by mrhirenmodi** [comment]
<select multiple="multiple" placeholder="-- Agency Name --" id="crruploadselection" class="form-group selAll"> <option value="Education">Education</option> <option value="Defence">Defence</option> <option value="Planning">Planning</option> <option value="Water">Water</option> </select>
