### ISSUE TITLE
triggerChangeCombined is not working when you combine multiple selection with single selection controls

### ISSUE THREAD

**Issue by killergege** [HemantNegi/jquery.sumoselect#189]
I have a small issue with triggerChangeCombined on v3.0.3.
I enabled it, along with okCancelInMulti on a batch of Selects elements, with "multiple" enabled, but it doesn't seem to always work.

**Update** : the following details are probably wrong, see my comments.
~~On my first try, I used `$("select").SumoSelect({...})` as I wanted to apply it to all Selects. but it still triggered a change event as soon as I checked an option, before I hit OK.
Then, when I changed it to `$("select.TestSelect").SumoSelect({...})` and applied a class TestSelect to the Select element, it worked as expected (change triggered when clicking OK).~~

~~Now I have the same issue in another very similar page with the same code and same class : `$("select.TestSelect").SumoSelect({...})`.
I'm trying to reduce the code in the page to find the culprit but in the meantime you might know what could cause the issue, so I'm posting here. I'll update if I find more details.~~

~~Please note that I'm using it on a ASP.NET page, with AjaxControlToolkit, so there are a lot of Javascript that I cannot control, maybe something is conflicting.~~

**Comment by killergege** [comment]
Strange thing : I have 8 select with Multiple enabled, but 1 where it's not. If I remove my class from it (hence it's not in the jQuery selector), the triggerChangeCombined works as expected.
Maybe it doesn't like combining multiple and single selection items in a same batch ?

**Comment by killergege** [comment]
Here is a JSFiddle https://jsfiddle.net/killergege/uyv8zqeo/
If you select an element in the first list, it triggers a change when it shouldn't.
If you add "multiple" to "#island2", it works.

**Comment by Zenoo** [comment]
It seems to work fine for me.  
Please note that `triggerChangeCombined` is `true` by default, so your example doesn't change the default behavior.
