### ISSUE TITLE
3.0.2 release missing isClickAwayOk support

### ISSUE THREAD

**Issue by isanoeben** [HemantNegi/jquery.sumoselect#192]
isClickAwayOk can be found in jquery.sumoselect.min.js copy on the git project home screen:

https://github.com/HemantNegi/jquery.sumoselect

however it's missing from the 3.0.2 release tag:

https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.0.2

Furthermore, the copy pulled in by bower is missing isClickAwayOk support.  This is my bower dependency:

  "dependencies": {
    "sumoselect": "^3.0.2"
  }

**Comment by mbardelmeijer** [comment]
@HemantNegi could you create a new release? 🤞

**Comment by iceuponfire** [comment]
i guess this is why isClickAwayOk does not work on my latest project. A fix would be awesome :) 🤞

**Comment by Zenoo** [comment]
There shouldn't be anymore problems regarding minified & unminified version being different for now on.  
Please upgrade your sumoselect version.
