### ISSUE TITLE
Dropdown focus on selected item

### ISSUE THREAD

**Issue by ashok31889** [HemantNegi/jquery.sumoselect#193]
when the page loads, I am loading 30 to 50 options and selecting one option as default.
After page loads completely, i can see the selected item by scrolling down the dropdown.
Without scrolling the dropdown, is it possible to bring it in front?
And after selecting new option and hits submit button, it should stay on same option. Should not move to top.

Let me know, how to overcome this

Thanks

**Comment by firstinstance** [comment]
hi, i have the same problem.

**Comment by firstinstance** [comment]
I have built a solution!

Use this after: jQuery(".select").SumoSelect ....
`jQuery('.select').on('sumo:opened', function(sumo) {
		    jQuery(this).parent().find(".options").scrollTop(jQuery(jQuery(this).parent().find(".options .opt.selected")).position().top - 60);
		});`

CSS for selected:
`.SumoSelect > .optWrapper > .options li.opt.selected { background-color: #e4e4e4; }

.SumoSelect > .optWrapper > .options li.opt.selected label { font-weight:bold; }`

**Comment by Zenoo** [comment]
PR #241 attempted to solve this.  
It still needs some work before being merged though.  
Feel free to help if you want ^^
