### ISSUE TITLE
Css file can break the Select All behavior

### ISSUE THREAD

**Issue by killergege** [HemantNegi/jquery.sumoselect#195]
With the v3.0.3, the "Select all" checkbox is not working properly (it behaves as a "normal" check box).

My css file seem to break the behavior of this checkbox: to prevent flickering I added a "display: none" to the select elements and I only display them once I ran the SumoSelect.
This seem to break the behavior. If I replace the "display: none" with "visibility: hidden", it works again, but it's a solution I don't like as the element still use space, so the elements move between first loading and the SumoSelect() call.

It broke when I updated my file (v3.0.3 one month ago to v3.0.3 ^^) to get the isClickAwayOk feature.

As a "quick fix", I edited the "toggSelAll" function : 
`O.E.find('option:not(:disabled,:hidden)')`
becomes
`O.E.find('option:not(:disabled)')`
Probably not the best fix but I don't have any hidden option so I don't care

**Comment by Zenoo** [comment]
Can't reproduce the bug with the current version, please upgrade your sumoselect version.
