### ISSUE TITLE
handling OK click with multiple instaces

### ISSUE THREAD

**Issue by vishalmarya** [HemantNegi/jquery.sumoselect#196]
This is not an issue. 

How do I identify the instance of my list for which OK button was clicked if I am using sumo select with 2 list boxes in same page.

Below is my code:

`
$(<%=ListBox1.ClientID%>).SumoSelect({ selectAll: true, okCancelInMulti: true });
$(<%=ListBox2.ClientID%>).SumoSelect({ selectAll: true, okCancelInMulti: true });

$('.btnOk').on('click', function ()
{
    alert('OK button Clicked');
});`

**Comment by tito433** [comment]
@vishalmarya,
OK button fires 'change' event if triggerChangeCombined:true and selection changed. Hence
`$(<%=ListBox1.ClientID%>).SumoSelect({ selectAll: true, okCancelInMulti: true,triggerChangeCombined:true });
$(<%=ListBox1.ClientID%>).on('change',function(e){
        alert('OK button Clicked');
    });`

Will fulfill your requirement (I guess!).
