### ISSUE TITLE
`unload()` only works with class selector and not with id selector

### ISSUE THREAD

**Issue by Rah1x** [HemantNegi/jquery.sumoselect#198]
Hi,

ive tried a lot and looks like the unload() only works if you have it called via class selector. For example the following will work:
`$('.selectme')[0].sumo.unload();`

But not the following even if you have the element id the id, and you have attached the sumoselect via id at the first place:
`$('#selectme_by_id')[0].sumo.unload();`

**Comment by Zenoo** [comment]
It does work, I just tried it.  
Feel free to reopen the issue if you managed to reproduce the bug.
