### ISSUE TITLE
Issue with "select All" in IE 

### ISSUE THREAD

**Issue by emilsonrod** [HemantNegi/jquery.sumoselect#200]
Hi all I have an issue in IE, I added the select all in true but it does not work, I checked the demo page and the issue is there as well. 
Steps
1 Set up the select all true
2 open in internet explorer
3 click drop down 
4 click select all
![demoselectallerror](https://cloud.githubusercontent.com/assets/5720157/25400176/bfd74e34-29bf-11e7-977d-57520b8e8deb.jpg)

Thanks for advance.

**Comment by schweeneh** [comment]
Hi @emilsonrod, 

I'm also working on this issue. I think the issue is on the following line:
https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js#L653

I.E. does not support hidding option elements so the pseudo selector :hidden makes the selector always find 0 elements. 

Not sure if the :hidden check is really necessary or not here. Removing it should fix the problem.

**Comment by jasonpjones** [comment]
@schweeneh 
Is there any status on this issue?

**Comment by HemantNegi** [comment]
Hi Everyone,
What version of IE are you using.
also what is the version of jquery.

**Comment by bcowell** [comment]
Also broken for me
IE 11
jQuery 1.9.1

**Comment by jasonpjones** [comment]
IE 11,
jquery 1.11.1

**Comment by jasonpjones** [comment]
@HemantNegi Is there a plan to have this issue addressed soon? I am in the final stages of a project but I need to be able to support IE, and need to know if I should start looking into a work-around. 

Has anyone verified the fix proposed by @schweeneh ?

Thanks!

**Comment by AlexKulikov** [comment]
@jasonpjones I've verified it - works fine. I also think that :hidden selector not needed there and just :disabled should be enough. There is a code later which doesn't allow to work with hidden elements anyway "if (e.hasClass('hidden')) return;"

**Comment by meterlongcat** [comment]
Just wanted to draw attention to a comment I left about this problem in IE in #216. Hope it's of some use.

**Comment by Zenoo** [comment]
This seems to work now.  
It must have been fixed down the line.  
Please update your sumoselect version to the latest.
