### ISSUE TITLE
"select All" is not working in IE

### ISSUE THREAD

**Issue by coolkushagra** [HemantNegi/jquery.sumoselect#201]
Hi all I have an issue in IE, I added the select all in true but it does not work, I checked the demo page and the issue is there as well.
Steps
1 Set up the select all true
2 open in internet explorer
3 click drop down
4 click select all

**Comment by EProd-Rhansen** [comment]
Are there a lot of options in the list to pick from?

**Comment by coolkushagra** [comment]
At one place Yes and others with fewer options.

**Comment by headstreamtech** [comment]
Select All doesn't work in IE in my case too.

**Comment by LukeMadhanga** [comment]
I can confirm that it also doesn't work in Chrome Version 58.0.3029.110 (64-bit). 

I have a pretty long list (1,023 options). When I filter the list to say around 30 items by searching and then click select all. $('select').val() only returns one item in the array.

If I click around in a random way, and then perform the filter and then the select all, all 30 items are then selected.

**Comment by meterlongcat** [comment]
Just wanted to draw attention to a comment I left about this problem in IE in #216. Hope it's of some use.
