### ISSUE TITLE
Multi Drop Down Select - List jumps always to Top after select

### ISSUE THREAD

**Issue by futureweb** [HemantNegi/jquery.sumoselect#202]
Hello,
using sumoselect for Multi-Ajax-Drop Down - when I scroll down the List and select an Item (STRG pressed)  the List jumps to the Top Entry after selection - making it rather hard to select Multiple Items in longer Lists ...
Could this be fixed somehow?
Thank you
Andreas Schnederle-Wagner

**Comment by Zenoo** [comment]
I can't reproduce this bug.  
Feel free to reopen this issue if you manage to reproduce the bug.
