### ISSUE TITLE
Dynamic position select when reached the page footer

### ISSUE THREAD

**Issue by DenisDov** [HemantNegi/jquery.sumoselect#205]
The problem is [http://prntscr.com/f9kqbw](http://prntscr.com/f9kqbw)
Hi, how to release this: when i reached the bottom of page, select now opened at top

**Comment by mcvova** [comment]
Is it any solution to this problem?

**Comment by Tejbahadur** [comment]
any solution for this issue. Due to this is not behaving a normal select box

**Comment by Zenoo** [comment]
You can use the `up` option to force the dropdown to open towards the top.  
```js
{
  up: true
}
```
