### ISSUE TITLE
How to make edit able select box

### ISSUE THREAD

**Issue by bob970** [HemantNegi/jquery.sumoselect#206]
I'm using this plugin, I'd like make search and editable select box.
I tried to set "search=true", the search feature is working but I can not edit. If the select box doesn't contain my inputted data, I want to add the data.
how can I implement this feature.

**Comment by mehmetkirkoca** [comment]
$('#yourElementId').SumoSelect({search: true});
This will work.

**Comment by Zenoo** [comment]
#275 Managed it with a very simple code.
