### ISSUE TITLE
Serious Performance Issues

### ISSUE THREAD

**Issue by LukeMadhanga** [HemantNegi/jquery.sumoselect#209]
I have a multiple select with 1023 options. If only one item is selected and then I use `$('select')[0].sumo.unSelectAll();`, it takes forever to unselect them all, whilst crashing the page. 

Select all is equally bad in terms of performance

**Comment by wqrana** [comment]
I am also facing such serious issue with sumo-select. I have only around 400 options for multi-select by using  "jquery.sumoselect - v3.0.3". when I click on Select All checkbox, my browser went in not responding state for around 1min. Same for UnSelect All by using $('select')[0].sumo.unSelectAll();

I just want to know, any plan to fix such serious issue or if it's already fixed then guide for latest code.

**Comment by Zenoo** [comment]
This should be fixed in [v3.3.2](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.2)
