### ISSUE TITLE
Remove item by value or data-attribute

### ISSUE THREAD

**Issue by nikto1** [HemantNegi/jquery.sumoselect#211]
As by title, it's not possible to remove an item by it's value or by data-*, only by index.
Would be very useful, e.g. in an ajax function which removes/ add dynamically the items inside the select. Actualy you can only search the item by it's data-val inside the  .optWrapper > .options li and then remove it.

**Comment by GraninV** [comment]
$(".class option[value='"+id+"']").remove();
$('select.class')[0].sumo.reload();

**Comment by Zenoo** [comment]
```js
const select = document.querySelector('.yourSelect');
$(select )[0].sumo.remove([...select.querySelectorAll('option')].findIndex(option => option.value == 'yourValue'))
```
