### ISSUE TITLE
New event when a option is clicked (code included)

### ISSUE THREAD

**Issue by pdavis42** [HemantNegi/jquery.sumoselect#212]
Here is code to implement a new event triggered when an option is selected.  This is useful because changes on the select don't indicate which item was changed in a multi-select.

This was used in a multi-select when clicking one option needed to force other options off.  An example would be a "None of the above" option.

```
*** 482,487 ****
--- 482,488 ----
                          if (O.is_multi) {
                              li.toggleClass('selected');
                              li.data('opt')[0].selected = li.hasClass('selected');
+                     	    O.E.trigger('sumo:optionclick', [O, li.data('opt')[0]]);
                              O.selAllState();
                          }
                          else {
```

Sample usage code:

```
$("#sel").on("sumo:optionclick", function(event, sumo, opt) {
    if (opt.selected && opt.value == 'abc') {
        sumo.unSelectItem('def');
    }
});
```
The event handler's 3rd parameter is the <option> element involved in the click.

**Comment by Attacking3rd** [comment]
Thanks for making this available pdavis42.  It helped me out today.

**Comment by Zenoo** [comment]
Listening to the select `change` event and checking the option you want yourself is easy enough I don't think we need to add this callback

**Comment by nikto1** [comment]
@pdavis42 thanks for it, really needed.
