### ISSUE TITLE
Ajax Autocomplete Feature

### ISSUE THREAD

**Issue by vinu-ganesan** [HemantNegi/jquery.sumoselect#218]
Could anyone help me to integrate the ajax autocomplete in this plugin?

Thanks!

**Comment by Zenoo** [comment]
How would that work? The search searches through the options.  
For the options to be searchable, they need to be fetched before you search, not after.

**Comment by Anubarak** [comment]
> How would that work? The search searches through the options. For the options to be searchable, they need to be fetched before you search, not after.

Yeah that's basically what all other selects do: integrate an option to fetch the results from endpoint and include the search parameter in that request. 

For example
- https://select2.org/data-sources/ajax
- https://github.com/Choices-js/Choices has an ajax Option as well (no example except a git issue tho)
