### ISSUE TITLE
Selected items

### ISSUE THREAD

**Issue by frkolyan** [HemantNegi/jquery.sumoselect#219]
Hi @HemantNegi ! How could I get selected items from multiple SumoSelect with jQuery code?
Is there any "getValues()" method, "value" prop or smth?

**Comment by wubzz** [comment]
@frkolyan Calling `$(element).val()` should return the value(s).

Better late reply than never..

**Comment by frkolyan** [comment]
Thank you for your response, I've already found this way to get values. I thought there were something like `$(element).sumo.getValue();`
