### ISSUE TITLE
okCancelInMulti not working after first non-multiple sumo select

### ISSUE THREAD

**Issue by isanoeben** [HemantNegi/jquery.sumoselect#220]
The ok/cancel buttons stop displaying on muti-select elements after the first sumo select that is a non-multiple, see jsfiddles below.  I believe the issue stems from line 81 `if(!O.is_multi)settings.okCancelInMulti = false` from here:

[https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js](https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js)

I don't understand why `settings.okCancelInMulti` would change if the select element has the `multiple` attribute or not.  If I comment line 81 then I get expected results.

All sumo selects working here, because they are all `<select multiple="multiple">`

[https://jsfiddle.net/w7283wka/11/](https://jsfiddle.net/w7283wka/11/)

Only the first sumo select works as expected here because the last two are after a single select element

[https://jsfiddle.net/w7283wka/10/](https://jsfiddle.net/w7283wka/10/)

**Comment by isanoeben** [comment]
Is there an ETA on when this fix will be released?

**Comment by Zenoo** [comment]
@isanoeben This appears to be fixed in the current version.  
Please update your sumoselect version.
