### ISSUE TITLE
selectedIndex -1 not working in IE

### ISSUE THREAD

**Issue by vladojovanovski** [HemantNegi/jquery.sumoselect#221]
If selectedIndex is set to -1 on the select (before initializing), SumoSelect will create elements and none of the will be selected under Chrome and Firefox. Under IE it will select the first option from the select, setting selectedIndex to 0.

My fix was adding two lines into createElems function:
1. line 71: var tmpselectedIndex = this.E[0].selectedIndex;
2. line 73 (now 74): O.E[0].selectedIndex = tmpSI;

Hope this helps someone.

**Comment by Zenoo** [comment]
Thanks ! This should be fixed in [v3.3.4](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.4)
