### ISSUE TITLE
Sumo select search text box is dispalying a dropdown list with dates when user click second time on search button in IE11

### ISSUE THREAD

**Issue by abhisheksinghbanarasi** [HemantNegi/jquery.sumoselect#223]
`Below` is the code i am using.

<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm1.aspx.cs" Inherits="WebApplication2.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <script src="../Scripts/jquery-1.11.1.min.js" type="text/javascript"></script>
    <script ### src="../Scripts/jquery.sumoselect.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            var $ddlGroup = $('#ddlGroups');
            sumoSelObj = $ddlGroup.SumoSelect({
                search: true, csvDispCount: 6,
                okCancelInMulti: true,
                triggerChangeCombined: true,
                selectAll: false
            });
        });
    </script>
</head>
<body>

    <form runat="server" method="post">
        <asp:DropDownList ID="ddlGroups" runat="server">
            <asp:ListItem Enabled="true" Text="Select Month" Value="-1"></asp:ListItem>
            <asp:ListItem Text="January" Value="1"></asp:ListItem>
        </asp:DropDownList>
    </form>
</body>
</html>

```

**Comment by abhisheksinghbanarasi** [comment]
I have noticed that if i remove form tag it works fine. But in my actual appication i cannoot remove form.

**Comment by piranout** [comment]
I'm experiencing the same (or a very similar) issue in Edge 41 (EdgeHTML 16).

It seems to be autocomplete entries showing up for the search box. When I tried using autocomplete="off" to suppress it, I could no longer get a carat in the search box (preventing entry of a search/filter string).

**Comment by Zenoo** [comment]
This should be fixed in [v3.3.5](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.5)
