### ISSUE TITLE
Bootstrap 4 Beta

### ISSUE THREAD

**Issue by krystyna93** [HemantNegi/jquery.sumoselect#224]
Hi,
Does anyone know if this is compatible with Bootsrap 4 beta???

**Comment by HemantNegi** [comment]
Somoselect is responsive, so it should be compatible.

**Comment by krystyna93** [comment]
Thanks for that, Cheers!

**Comment by bbapp** [comment]
Bootstrap beta.2 is creating problems for me. The select menu height is too low and I can't figure out which CSS rules are specifically causing the problem. All I know is that disabling Bootstrap resolves the issue.

https://imgur.com/a/xLGTS
