### ISSUE TITLE
Optgroup Support has a wired bug

### ISSUE THREAD

**Issue by Fayne** [HemantNegi/jquery.sumoselect#227]
I found if I have some optgroup, it will broken item index. 

For example: http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html `Optgroup Support` demo:

If I run `$('.optgroup_test')[0].sumo.disableItem(22);`, it will throw `Uncaught index out of bounds` exception. But 22 is correct index.

**Comment by drango** [comment]
22 is not a correct index. In the optgroup_test correct index is from 0 to 19 (20 items). 
But event if you run $('.optgroup_test')[0].sumo.disableItem(19); there is still a bug with visual representation of the disabled option. 
Change line 627 to: 
if(!O.mob)O.optDiv.find('ul.options li.opt').eq(i).toggleClass('disabled', c).removeClass('selected');
And line 724 to:
if(!O.mob)O.optDiv.find('ul.options li.opt').eq(i).remove();

"li.opt" opt class is important in this fix. I hope this helps to you @Fayne .

**Comment by Fayne** [comment]
Thank you so much @drango .  It helps a lot.

**Comment by LimpEmu** [comment]
Thank you so much for your comment @drango . I finally realized this is a bug after trying to get this to work for 2 hours!

**Comment by Zenoo** [comment]
This should be fixed in [v3.3.6](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.6)
