### ISSUE TITLE
lazy load feature

### ISSUE THREAD

**Issue by mehmetkirkoca** [HemantNegi/jquery.sumoselect#231]
Hi I am using this plugin into my projects. I have lots of datas. I'am using eagerloadin. Can I use this plugin lazyloading some how. If I can how should I do. I wanned to type in some words and retive related datas from database. I hope I can find solution here. 
Thanks for any help. I would appreciate about any solution.

**Comment by HemantNegi** [comment]
Currently this feature is not available. you can use [https://harvesthq.github.io/chosen/](https://harvesthq.github.io/chosen/) instead
