### ISSUE TITLE
A possible option to conduct search on a URL

### ISSUE THREAD

**Issue by rehmatworks** [HemantNegi/jquery.sumoselect#232]
Thanks for this awesome plugin. I'm requesting a feature related to search. Please introduce an `onSearch` event or add support for a remote URL where a `GET` or `POST` request will be made and the data will be returned for consumption (i.e. to be appended to the select dropdown). I hope this feature will help several others as well.

**Comment by Zenoo** [comment]
It seems counter-intuitive to me to be able to search through options that are not already in the select.  
Options should be fetched before being able to search through them.
