### ISSUE TITLE
sels is not defined error

### ISSUE THREAD

**Issue by micheniverse** [HemantNegi/jquery.sumoselect#233]
In the setText function, sels will error out with a not defined error in typescript (along with the for loop because i is not explicitly typed) in typescript.

**Comment by alboth** [comment]
same here

line 501 is:
`sels = O.E.find(':selected').not(':disabled'); //selected options.`
should be
`var sels = O.E.find(':selected').not(':disabled'); //selected options.`

line 553 is:
`for (i = 0; i < settings.nativeOnDevice.length; i++) ...`
should be
`for (var i = 0; i < settings.nativeOnDevice.length; i++) ...`

**Comment by Napalm005** [comment]
issue at min.js remain

**Comment by benwebbbenwebb** [comment]
@HemantNegi would it be possible to have the jquery.sumoselect.min.js re-created to resolve the issue when pulling the minified file?
Thanks!

**Comment by Zenoo** [comment]
This issue seems already fixed.  
Feel free to reopen the issue if you still have trouble with it.
