### ISSUE TITLE
unSelectAll not working on single select dropdown with placeholder

### ISSUE THREAD

**Issue by hobwell** [HemantNegi/jquery.sumoselect#238]
With a single select dropdown (containing a placeholder) unSelectAll does not clear the selection and re-display the placeholder, which is the behavior I would expect.

Using unSelectItem(\<idx\>) did the appropriate thing (clear selection, re-display placeholder), but using unSelectAll should do the same without having to know the selected index.

Please see [the fiddle ](https://jsfiddle.net/c4g8pbLq/11/).

To get the placeholder to appear at all I had to include the 'size' attribute on the select tag (which may be a separate issue).

**Comment by Zenoo** [comment]
This should be fixed in [v3.3.7](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.7)
