### ISSUE TITLE
How can we get the selected item in tab keypress

### ISSUE THREAD

**Issue by AbdulShaikh** [HemantNegi/jquery.sumoselect#240]
Is there any way to get the selected item in sumoselect when user press the tab btn.
Here is the steps to reproduce the scenario.

Suppose SumoSelect populated with items now user press tab button to get the focus on sumo dropdown from previous control, now user is pressing the down arrow that will display all the items, user can select the desired item by keep pressing the down arrow key, but after selected the desire item pressing the Tab button should not select that item in dropdown it's ignored it. How can we get that item selected in Tab keypress.

**Comment by AbdulShaikh** [comment]
@HemantNegi Thank you for this great plugin, Kindly suggest anything to get this done.

**Comment by mehulsinh-vaghela-coder** [comment]
@AbdulShaikh , Can you tell me how you resolved this issue?
