### ISSUE TITLE
Search results include opt groups with no matches

### ISSUE THREAD

**Issue by zachrybaker** [HemantNegi/jquery.sumoselect#242]
I believe that searching is flawed. Here's the behavior I would expect:
1. Search text should find both matching groups and values where:
2. Groups and values that do not match should both be hidden
3. Matching groups should show all of their values even if the values themselves don't match the search text

As it is, if a list of groups is fairly long, it can be really difficult to find the entry you are looking for.  It should instead appropriately filter it to make selection effortless.

Finally, it is possible that other users need a different behavior.  In this case, you could expose an event to allow for results filtering based on the desired outcome, or you could add CSS classes that would get us there.  Thanks

**Comment by Bill-TEGNA** [comment]
I'll second this comment.  I have 10-12 option groups with 5-10 options within them.  It would be great to not see the unmatched groups.

**Comment by Bill-TEGNA** [comment]
I have a temporary workaround.  

- Search for `<0,i.toggleClass("hidden",s.hidden)` in the minimized version, and add `,i.parent().parent().toggleClass("hidden",s.hidden)` immediately after that.
- Search for `s.find("em").text(t.ftxt.val()),t.selAllState();`, and add `hideSumoOptGroups(e,t)` immediately after that.
- Add the following code block under the minimized js code

`function hideSumoOptGroups(e,t)
{
	t.optDiv.find("ul.options li.opt").not(".hidden").each(function(l,i){
	var i=e(i);
	i.parent().parent().removeClass('hidden');		
});`

**Comment by Zenoo** [comment]
This should be fixed in [v3.3.8](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.8)
