### ISSUE TITLE
Disable detecting select when dropdown is closed.

### ISSUE THREAD

**Issue by dawcza3** [HemantNegi/jquery.sumoselect#246]
I'm currently occured problem with valid selection items in my dropdowns. As you can see in the picture below, whenever i click on other space (not in dropdownsection), my items is detect like a selected (but not marked with check box in ui). 

![image](https://user-images.githubusercontent.com/16191056/36383638-0448e910-158d-11e8-84aa-e3ec35d965b0.png)

Is there any way to stop this unwanted behaviour ?  This is my html where i'm place my select item:

![image](https://user-images.githubusercontent.com/16191056/36383742-676d94be-158d-11e8-8e53-5eb2eaedd0f6.png)

Or maybe i'm setup something wrong with options ? This code i use to start my selector sumo select : 

**    $('#yearSelect').SumoSelect({ placeholder: 'Wybierz Rok' });**

**Comment by Zenoo** [comment]
Set the `selectedIndex` of your `<select>` to `-1` before initializing: 

```js
$('#yearSelect')[0].selectedIndex = -1;
$('#yearSelect').SumoSelect({ placeholder: 'Wybierz Rok' });
```
