### ISSUE TITLE
Unable to reset the selected field values

### ISSUE THREAD

**Issue by mrhirenmodi** [HemantNegi/jquery.sumoselect#247]
Hi, I have used this sumoselect library for the dropdown below but I am not able to write jquery function to reset the previously selected value. Could you please help me?
<div class="list-group-item">
			<span class="form-group"><b><strong> Agency Name
						: </strong></b></span> &nbsp;&nbsp;&nbsp;&nbsp; <select multiple="multiple"
				placeholder="-- Agency Name --" id="crruploadselection"
				class="form-group selAll">
				<option value="Education">Education</option>
				<option value="Defence">Defence</option>
				<option value="Planning">Planning</option>
				<option value="Water">Water</option>
			</select>
		</div>

**Comment by mrhirenmodi** [comment]
<div class="list-group-item">
			<span class="form-group"><b><strong> Agency Name
						: </strong></b></span> &nbsp;&nbsp;&nbsp;&nbsp; <select multiple="multiple"
				placeholder="-- Agency Name --" id="crruploadselection"
				class="form-group selAll">
				<option value="Education">Education</option>
				<option value="Defence">Defence</option>
				<option value="Planning">Planning</option>
				<option value="Water">Water</option>
			</select> <br>
			<br>
			<button type="button" id="crrUpload"
				class="ui-button-primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
				role="button">
				<span class="ui-button-text">Submit</span>
			</button>
		</div>

**Comment by mrhirenmodi** [comment]
<div class="list-group-item">
			<span class="form-group"><b><strong> Agency Name
						: </strong></b></span> &nbsp;&nbsp;&nbsp;&nbsp; <select multiple="multiple"
				placeholder="-- Agency Name --" id="crruploadselection"
				class="form-group selAll">
				<option value="Education">Education</option>
				<option value="Defence">Defence</option>
				<option value="Planning">Planning</option>
				<option value="Water">Water</option>
			</select> <br>
			<br>
			<button type="button" id="crrUpload"
				class="ui-button-primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
				role="button">
				<span class="ui-button-text">Submit</span>
			</button>
		</div>

**Comment by mrhirenmodi** [comment]
<select multiple="multiple"
					placeholder="-- Agency Name --" id="crruploadselection"
					class="form-group selAll">
					<option value="Education">Education</option>
					<option value="Defence">Defence</option>
					<option value="Planning">Planning</option>
					<option value="Water">Water</option>
				</select>

**Comment by gabrfuk** [comment]
Can you please give some details of the code, so I can understand better what's the issue here?

**Comment by maheshKDS** [comment]
Hi, i get same issue,
 i m just adding "sumo" select option dynamically not static, but i can't back normal select element when i was apply 'Reload' method of 'Sumo' 

see example blow in image


![sumo](https://user-images.githubusercontent.com/39260766/41685232-6b3b28c0-74fd-11e8-8878-ccff7b509bd5.png)

**Comment by Zenoo** [comment]
If you want to remove the plugin, simply do
```js
$('.yourSelect')[0].sumo.unload();
```
If you want to reload it:
```js
$('.yourSelect')[0].sumo.reload();
```
