### ISSUE TITLE
sumoselect dropdown display issue

### ISSUE THREAD

**Issue by Naveencheekoti** [HemantNegi/jquery.sumoselect#248]
![sumoselect](https://user-images.githubusercontent.com/23651242/36442660-7fcdd1e4-169c-11e8-8493-87cf0c3dab73.PNG)
The sumoselect drop down section is hidden and form field  with checkboxes are not showing properly.I have tried with different z-index values to bring the sumoselect to the front with no luck.

.SumoSelect>.optWrapper{ position:absolute; }
I also tried above code.But It is adding the space between the form elements.Is there a way to show the drop down  options without effecting the form elements and form field to show properly with checkboxes.

**Comment by kalyangithubuser** [comment]
Yes, Even i have the same issue.

**Comment by MadTomT** [comment]
Anyone find a solution to this ? I have the same issue when called in a popup window.

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?
