### ISSUE TITLE
Placeholder only works with multiple?

### ISSUE THREAD

**Issue by maggenti** [HemantNegi/jquery.sumoselect#249]
Placeholder only works with multiple. IT will not work on any single select. Even when you explicitly add placeholder="some text" instead of multiple nothing will happen. Placeholder will only display when you include add the word multiple?
First example: This will display the placeholder text
<select name="first_example" value=" " required="" multiple="multiple" id="some-1st-id">
$('.fol').SumoSelect({ placeholder: 'First Example' });
Second example: This will not display the placeholder text
<select name="second_example" required="" value=" " id="some-2nd-id">
$('.fol').SumoSelect({ placeholder: 'Second Example' });

**Comment by kalmukvitaly** [comment]
Seem, you are right. But you can add option with attributes: disabled and selected. It will be the placeholder.

**Comment by maggenti** [comment]
Well thanks for that I already figured that out.  My problem is that I
wanted to use the placeholder as a blank so I can use an custom svg image
for each individual pulldown.  Since I can not use the placeholder, do you
have a way to do that?  I would appreciate any help you can lend me, thanks
for your time.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ecobux** [comment]
I also need a placeholder for a single select. How exactly did you do that?

I added one option at the start with selected="selected" disabled="disabled" but then when I open the menu it also appears as (disabled) first option:
![screenshot-2018-4-5 tgp dynamic post filter groups_only 0 wp-test local](https://user-images.githubusercontent.com/1910838/38374658-85851c9e-38f4-11e8-8d0a-2b5039975996.png)

Could you point me to the place in the code where to enable placeholders for single selects? Thanks!

**Comment by DSergioD** [comment]
**Modify multiple select with jQuery like this:**
$('.SumoSelect').each(function () { var $this = $(this); $this.find('> .optWrapper.multiple .options li.opt').on('click', function () { $(' .SumoSelect > .optWrapper.multiple > .options li.opt').removeClass('selected'); $(this).addClass('selected'); var $labelText = $(this).find('label').text(); $this.find('.CaptionCont').attr('title', $labelText); $this.find('.CaptionCont > span').text($labelText); }); });

**Comment by Zenoo** [comment]
Simply set the `selectedIndex` from your `<select>` to `-1` before initializing:

```js
$('.yourSelect')[0].selectedIndex = -1;
$('.yourSelect').SumoSelect();
```
