### ISSUE TITLE
Firing click events on disabled items

### ISSUE THREAD

**Issue by impcyber** [HemantNegi/jquery.sumoselect#25]
If option was disabled by default and enable programmatically it will have no `click` event:
```javascript
if (opt.attr('disabled') || opt.parent('optgroup').attr('disabled'))
    li.addClass('disabled');
else
    O.onOptClick(li);
```
And if option was disabled programmatically it will still have `click` event.

Because createLi method calls only once during initialization for each option.

You may see the test here: http://jsfiddle.net/xp4kf9kx/2/

**Comment by HemantNegi** [comment]
Thanks for this bug,
will be fixed in next version

Cheers!!
