### ISSUE TITLE
Prevention against XSS

### ISSUE THREAD

**Issue by akshayvadher** [HemantNegi/jquery.sumoselect#250]
Current version of SumoSelect happens to execute code and vulnerable to XSS.

Example given https://jsfiddle.net/vLet1a0k/5/

![image](https://user-images.githubusercontent.com/2619644/36586031-27e08952-18a6-11e8-9174-0218ccdcd1f3.png)

Maybe the plugin should give option to handle XSS out of box.

**Comment by praulins** [comment]
yes indeed

**Comment by Rochet2** [comment]
Would be great to have this fixed, having the same issue.
Related PR for people interested in a fix https://github.com/HemantNegi/jquery.sumoselect/pull/145

**Comment by xhienne** [comment]
See patch at https://github.com/HemantNegi/jquery.sumoselect/pull/145#issuecomment-512883686

**Comment by YotamAlon** [comment]
I am experiencing this issue as well.
Any estimate on when 3.0.3 will be released?

**Comment by Zenoo** [comment]
The last vulnerabilities were fixed in cd19c625d98858e2d9f6edef3c343d402ddf32bd
