### ISSUE TITLE
How get only clicked option value

### ISSUE THREAD

**Issue by Gordey** [HemantNegi/jquery.sumoselect#251]
Hi Hemant,

how i get only clicked option value in multiselect mode?
This is my [jsfiddle](https://jsfiddle.net/MaxGordey/97pp4dLz/2/)

Thanks

**Comment by gabrfuk** [comment]
I believe you can use the native jQuery selected selector to solve this issue, here's an example of your case:

<select multiple="multiple"  placeholder="Hello  im from placeholder" class="SelectBox" required>
       <option value="volvo">Volvo</option>
       <option value="saab">Saab</option>
       <option value="mercedes">Mercedes</option>
       <option value="audi">Audi</option>
       <option value="bmw">BMW</option>
    </select>

$('.SelectBox **option:seleted**').on('change', function() {
	alert($(this).val());
});


This is gonna return all the options selected.

For more details about how the operator works check te link below:

https://api.jquery.com/selected-selector/

**Comment by maheshKDS** [comment]
@gabrfuk  can u explain by 'sumo' plugin  because above ur reference not working.
its return all value not a single select value


 $("#ddlCPT")
              .change(function () {
                  var str = "";
                  $("#ddlCPT option:selected").each(function () {
                      str += $(this).text() + " ";
                  });
                  console.log(str)
              })
              .trigger("change");


its return value when i was select one option
as
sunday
sunday,monday
sunday,monday,tuesday etc

**Comment by Zenoo** [comment]
You can get the select value by using:
```js
$('#yourSelect').val();
```
