### ISSUE TITLE
Handling events not work on android devices

### ISSUE THREAD

**Issue by Lajdak** [HemantNegi/jquery.sumoselect#252]
Hi Hemant,

i am using version 3.0.3 and I need use events but it don't work on android devices. On desktop (Firefox/Chrome) is everything OK. Is there some solution?

Working [fiddle](https://jsfiddle.net/5dy8j54n/6/)

```
// .class pointing to <select> tag
$('.class').SumoSelect({placeholder: 'Select choice'});

$('select').on('sumo:closed', function(sumo) {

    alert("Drop down closed!");
});
```

**Comment by vangama** [comment]
any solution for this?

**Comment by Zenoo** [comment]
Native selects don't send any custom events.  
You can set `forceCustomRendering` to `true` in the SumoSelect parameters to solve this.
