### ISSUE TITLE
sumoselect support for typescript

### ISSUE THREAD

**Issue by yuawei** [HemantNegi/jquery.sumoselect#253]
Can you rewrite sumoselect support for typescript ?

**Comment by ruudboon** [comment]
+1

**Comment by Zenoo** [comment]
I'm not a Typescript expert, so if anyone wants to handle this, feel free !  
I'll probably get around to it when everything else is solved, if no one did it before.

**Comment by Zenoo** [comment]
This should be fixed in [v3.4.9](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.4.9)
