### ISSUE TITLE
How to trigger open event

### ISSUE THREAD

**Issue by 2gracia** [HemantNegi/jquery.sumoselect#254]
I am using this plugin in my project. I have hide it, and when I click the button i show it and open by toggling "open" class in ".SumoSelect"  selector. It works, but on mobile it does not. Have anybody same problem? How can I solve this?

**Comment by Zenoo** [comment]
You can hide/show the options with the methods
```js
$(...)[0].sumo.showOpts();
$(...)[0].sumo.hideOpts();
```

If you still have trouble on mobile, set `forceCustomRendering` to `true`.  
Native select events can be a pain to deal with.
