### ISSUE TITLE
captionformatallselected not functioning

### ISSUE THREAD

**Issue by YairHadari** [HemantNegi/jquery.sumoselect#255]
Hi,
I"m trying to customize the captionformatallselected option.
Unfortunately I"m still getting the default value.

<select class="form-control testselect2 SumoUnder" captionformatallselected="AAAAA" placeholder="choose files" multiple="multiple" name="Recipients[r_rg_id][]" id="Recipients_r_rg_id" tabindex="-1">
<option value="3">AA</option>
<option value="165">BB</option>
<option value="2958">CC</option>
</select>

Regrds,
Yair

**Comment by Zenoo** [comment]
`captionFormatAllSelected` won't display if there are disabled options in the select, since they aren't selected.  
`captionFormat` will be displayed instead.
