### ISSUE TITLE
Enhancement Multiple Columns

### ISSUE THREAD

**Issue by sarvesh** [HemantNegi/jquery.sumoselect#257]
Hi Hemanth,

Kudos to your incredible work. 
Would like to check with you if you are supporting the display of multiple columns.
Eg: Multi Select-Multi Column
We would like to use in our project. Your code is easy to maintain.
Let us know, if you have any sample implementation for the same

**Comment by HemantNegi** [comment]
Its doable by simple css. https://jsfiddle.net/HemantNegi/84Lr72zw/
