### ISSUE TITLE
Multiple selection on mobile does not work

### ISSUE THREAD

**Issue by jc5826** [HemantNegi/jquery.sumoselect#259]
Tested with chrome's developer tools and iphone 6/7/8 simulation. If you click on a multiple select field it does not show a dropdown, instead it automatically selects the first option.  You can see this on the Demo page.

**Comment by elvisef** [comment]
For me it is still not working on mobile device. Tested on Samsung J7 2018.
In Chrome simulation it is working well for me, but on a real device it's not.

**Comment by s-pyadyshev** [comment]
Has the same issue

**Comment by rafachacon** [comment]
Seems to work fine when adding `forceCustomRendering: true` to the config.

**Comment by vanboom** [comment]
For me the multi select works perfectly on Android and iPad mobile devices, but in the Chrome simulator, the options window does not show.

**Comment by Zenoo** [comment]
`forceCustomRendering` is the way, if the native one is giving you trouble.
