### ISSUE TITLE
'select all' feature not work in safari v11.0

### ISSUE THREAD

**Issue by rpf5573** [HemantNegi/jquery.sumoselect#260]
'select all' feature in safari not work in your [live demo](http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html)

Check please!

**Comment by scrobbleme** [comment]
Same here. Not working in Chrome or Firefox either.

**Comment by sbraaa** [comment]
look at this: https://github.com/HemantNegi/jquery.sumoselect/issues/216#issuecomment-343297503
