### ISSUE TITLE
Race condition in FOR loop while using selectItem()

### ISSUE THREAD

**Issue by pepo1** [HemantNegi/jquery.sumoselect#264]
This is similar to the issue posted here: https://github.com/HemantNegi/jquery.sumoselect/issues/169 

The following code gets listings from a database and pre-populates a SumoSelect multi-select box, AND pre-checks an item if it has a numeric key.

```
for(i=0; i<3; i++){
    var slider_listing_id = res.DATA.LISTING_ID[i];
    var val = res.DATA.RECORD_ID[i];
    var text = res.DATA.TITLE[i];
    //alert(isNumeric(slider_listing_id)); //This alerts all three rows
    returnSelect[0].sumo.add(val,text);
    if(isNumeric(slider_listing_id)){
        //alert(slider_listing_id); // this alerts all three rows IF the line below is 
        //commented out, otherwise it only alerts two rows.
        returnSelect[0].sumo.selectItem(i);         
    }
}

```
The problem is that there seems to be a race condition going on and the code seems to skip a loop while calling

`returnSelect[0].sumo.selectItem(i); `

within each loop

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?
