### ISSUE TITLE
csvDispCount off by 1

### ISSUE THREAD

**Issue by ameyajoshi88** [HemantNegi/jquery.sumoselect#267]
According to the documentation:

_csvDispCount (int) The number of items to be displayed in the widget seperated by a , after that the text will be warped as 3+ Selected. Set 0 for all the options._

So, when I specify csvDispCount: 4, I expect the following:

<=4 selected - The select box should display the labels in comma separated format
\>4 selected   - The select box should display 'n Selected'

However, right now it will behave as follows:

<=3 selected - The select box will display the labels in comma separated format
\>3 selected   - The select box will display 'n Selected'

I would recommend changing
```
for (var i = 0; i < sels.length; i++) {
    if (i + 1 >= settings.csvDispCount && settings.csvDispCount) {
        if (sels.length === O.E.find('option').length && settings.captionFormatAllSelected) {
            O.placeholder = settings.captionFormatAllSelected.replace(/\{0\}/g, sels.length) + ',';
        } else {
            O.placeholder = settings.captionFormat.replace(/\{0\}/g, sels.length) + ',';
        }

        break;
    }
    else O.placeholder += $(sels[i]).text() + ", ";
}
```

to

```
if (settings.csvDispCount && sels.length > settings.csvDispCount) {
    if (sels.length === O.E.find('option').length && settings.captionFormatAllSelected) {
        O.placeholder = settings.captionFormatAllSelected.replace(/\{0\}/g, sels.length) + ',';
    }
    else {
        O.placeholder = settings.captionFormat.replace(/\{0\}/g, sels.length) + ',';
    }
}
else {
    for (var i = 0; i < sels.length; i++) {
        O.placeholder += $(sels[i]).text() + ", ";
    }
}
```

in the **setText function** to fix the issue as well as make the code cleaner.

**Comment by Zenoo** [comment]
Thanks ! This should be fixed in [v3.3.1](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.1)
