### ISSUE TITLE
limit number of selections?

### ISSUE THREAD

**Issue by MACscr** [HemantNegi/jquery.sumoselect#268]
With multiple="multiple" on the select, the user can select as many options as they want. Is there a way to limit them to X number? Maybe i only want them to be able to select 2 or 3. Heck, maybe for this particular user i only want it ot be 1, but i dont want to have to create a completely different set of select logic, etc.

**Comment by Zenoo** [comment]
The new `max` option released in [v3.2.0](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.2.0) allows you to do exactly that.
