### ISSUE TITLE
Change event not triggering when using addEventListener

### ISSUE THREAD

**Issue by Zenoo** [HemantNegi/jquery.sumoselect#269]
Selecting an option doesn't trigger the native `change` event, for some reason.

Using `addEventListener('change', ...)` doesn't work.

See an example here : https://jsfiddle.net/Zenoo0/L6ya2zmq/

**Comment by Zenoo** [comment]
#270 Fixes this issue, as shown here : https://jsfiddle.net/Zenoo0/L6ya2zmq/6/

**Comment by stlrnz** [comment]
Too bad this did not get merged. :(

**Comment by Zenoo** [comment]
@stlrnz This has now been merged.
