### ISSUE TITLE
Support for icons and customize options

### ISSUE THREAD

**Issue by Elimil** [HemantNegi/jquery.sumoselect#272]
Made this simple change to get support for custom css and icons for the options
usage with options is simple:
`<option value='xx' data-icon='fa-windows' data-class='boldtext'>Option</option>`

 `createLi: function (opt, d) {
                    var O = this; 
                    var c = opt.data("class");
                    var icon = "";
                    if (opt.data("icon") != "") {
                        icon = "<i class='fa fa-fw " + opt.data("icon") + "'></i>";
                    } 
                    if (!opt.attr('value')) opt.attr('value', opt.val());
                    var li = $('<li class="opt '+c+'"><label>'+ icon + opt.text() + '</label></li>');`

/Matti

**Comment by d3stroyahh** [comment]
fuck you
genius

**Comment by d3stroyahh** [comment]
ok i'll go a step further.
use this for custom images or font awesome ones
`createLi: function (opt, d) {
                    var O = this;

                    var c = opt.data("class");
                    var icon = "";

                    if (opt.data("icon") != undefined) {
                        icon = "<img style='height:16px;margin-right:6px;' src='" + opt.data("icon") + "'></img>";
                    }
                    else if (opt.data("iconfw") != undefined) { icon = "<i style='height:16px;margin-right:6px;' class='fa fa-fw " + opt.data("iconfw") + "'></i>"; }

                    if (!opt.attr('value')) opt.attr('value', opt.val());
                    if(icon != '') var li = $('<li class="opt"><label>'+ icon + opt.text() + '</label></li>');
                    else var li = $('<li class="opt"><label>' + opt.text() + '</label></li>');`

usage
<option data-icon='/images/myimagecustom.svg' value='myval'>myval</option> 
or FA 
<option value='myval' data-iconfw='fal fa-mobile'>Mobile</option>

**Comment by Zenoo** [comment]
The new `renderLi` option in [v3.3.0](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.0) allows you to render your options as you want them to be.  
You can add your icons here.  

```js
{
  renderLi: (li, originalOption) => {
    // Edit your li here
    return li;
  }
}
```
