### ISSUE TITLE
Can't focus to another input element while select dropdown is open

### ISSUE THREAD

**Issue by akindemirci** [HemantNegi/jquery.sumoselect#277]
Hello,

Thank you very much for this great library!

I have this little problem. While sumoselect dropdown is open, I can't move focus to another input element with one click. The focus remains on sumoselect element and it requires another click to move the focus to another element in the page. Here's a screencast:
https://www.dropbox.com/s/pni45qbxfrx08h8/sumoselect_focus.mp4?dl=0

My suggestion to fix this issue is to comment out this line in the definition of "hideOpts" function (line#376):

```
$(document).off('click.sumo');
// O.select.focus();
$('body').removeClass('sumoStopScroll');
```

It doesn't seem the break anything, but you'd know better.

Thanks!

**Comment by Zenoo** [comment]
Great catch !  
This should be fixed in [v3.1.5](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.1.5)
