### ISSUE TITLE
When options obj prop 'isClickAwayOk: true', the sumo:closed and sumo:closing events do not fire when clicking away from dropdown

### ISSUE THREAD

**Issue by kennsorr** [HemantNegi/jquery.sumoselect#279]
If 'isClickAwayOk' is set to 'true', clicking away from the dropdown/causing it to close should be the same as clicking the OK button after selecting new options.  Instead, while clicking away does indeed update the placeholder with the selected options (as if you pressed OK), clicking away does NOT fire the 'sumo:closed' or 'sumo:closing' events that are fired when pressing OK.

**Comment by Zenoo** [comment]
This seems to work on my end.  
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?
