### ISSUE TITLE
isMobile method "for" issue

### ISSUE THREAD

**Issue by ypanshin** [HemantNegi/jquery.sumoselect#28]
In my code I am working with extensions methods on Array prototype. And I have a issue with method "isMobile". The method has "for" that run on a collection "settings.nativeOnDevice" without checking if the collection has has own a property. Without the check the method throw exception when try to accept to extension method on the collection.
Could you please add validation to the method if the collection has own the property or to change it to regular for with index ? 

Example:
```javascript
isMobile: function () {
   var ua = navigator.userAgent || navigator.vendor || window.opera;
   for (var i in settings.nativeOnDevice)
        if (settings.nativeOnDevice.hasOwnProperty(i))
           if (ua.toLowerCase().indexOf(settings.nativeOnDevice[i].toLowerCase()) > 0)
               return settings.nativeOnDevice[i];
   return false
}
```

Thanks

**Comment by HemantNegi** [comment]
Will be fixed in next version
cheers!!
