### ISSUE TITLE
Customize Selection checkbox option

### ISSUE THREAD

**Issue by ad-sumit** [HemantNegi/jquery.sumoselect#284]
Hello Hemant,

First of all thank you very much for sumoselect library.

This is not an issue.

I used this and its work fine. But i am facing some issue to implement given requirement. There is some scenario which i need to implement using Sumoselect Js. I used Jquery as usual to checked and unchecked checkbox and it can but on server checked checkbox goes blank value. Even "OK" button also not working. Below are the scenario.

There is a 6 dropdown using sumoselect. And we need to change logic in Date and month dropdown as below.

1) Date dropdown has all Monday dates of current year and also added optgroup for grouping date like "This Month", "Previous Month", "Three Month" and "Six Month" at end. Default need all Monday dates are checked and "grouping date" are unchecked.

2) From Optgroup "grouping date" only 1 select at a time and once grouping date select all Monday date are unchecked. And as per selection from grouping date "Month Dropdown" also affected. For example, if someone select "Three Month" (Grouping checkbox) so month dropdown has only selected checkbox of last 3 months.

3) All this things done vice versa. Means if some one select and "Monday Date" then unchecked optGroup grouping checkbox.

I used jQuery prop property to checked and unchecked checkbox and add remove selected class. Its working but Click event not post values in SQL Queries. I think i am doing something wrong or sumoselect js override it. I write below code for implement same.

   
   $('.grp-date').prop('checked',false).removeClass('selected');

   
   $('.group .grp-date').on('click',function(){
		$('.grp-date').not(this).prop('checked',false).removeClass('selected');
		$('.alldates').prop('checked',false).removeClass('selected');
    });
   
   
    $('.sumo_filter_week_start_date .select-all').on('click', function() {
		$('.alldates').prop('checked',true).addClass('selected');
		$('.grp-date').prop('checked',false).removeClass('selected'); 
   });

   
   $('.alldates').on('click',function(){
		$('.grp-date').prop('checked',false).removeClass('selected');
   });

![screenshot-localhost-2019 11 07-19_55_29](https://user-images.githubusercontent.com/57499571/68470069-5dea7e00-0241-11ea-9a70-133ce39ab08e.png)

Please help me out.

Thanks & Regards
Sumit Patel

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?
