### ISSUE TITLE
Select all does not select items which contain double qoutes

### ISSUE THREAD

**Issue by pratikmane1299** [HemantNegi/jquery.sumoselect#289]
I have a select with some options. Some of them have double qoutes in them. When i click on select all, nothing is selected, the select all functionality doesn't work.
If i remove those qoutes from the options than it work properly, but I can't remove those qoutes cause they are required.

**Comment by Zenoo** [comment]
It seems to work on my end.  
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?
