### ISSUE TITLE
Page won't load in i.e. 11 / works in chrome

### ISSUE THREAD

**Issue by rconety** [HemantNegi/jquery.sumoselect#291]
Unhandled exception at line 304, column 9 in http://localhost:59645/Interface.aspx
0x800a1391 - JavaScript runtime error: 'MainContent_TabContainerInterface_TabPanelInterface_cblEngines' is undefined occurred

<script type="text/javascript">    
    
    $(document).ready(function () {
        $(MainContent_TabContainerInterface_TabPanelInterface_cblEngines).SumoSelect({ selectAll: true });
    });
</script>

**Comment by Zenoo** [comment]
This should be fixed in [v3.1.4](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.1.4)
