### ISSUE TITLE
In case dynamic dependent multi-select filter 

### ISSUE THREAD

**Issue by priya8421** [HemantNegi/jquery.sumoselect#295]
I have problem in case of 16 drop down all are dynamic and every drop down in dependent on selected drop down. 
Example : if  i select 3 rd drop down  first then click on ok button then remaining 15 drop down values should refresh with new options.
i have done with new options values with filter code but sumo.reload removed previous select box . 
var numItems = $('.filter-box').length;
			for(i=0;i<numItems;i++)
			{
			 $('.filter-box')[i].sumo.reload({placeholder: 'first'}); 	 
			}

**Comment by atulb-webonise** [comment]
Same Issues is occurring at my side I have 3 dependent select dropdowns. @HemantNegi

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?
