### ISSUE TITLE
Is there a way to allow using up and down arrow to select an item when also enabling the searchbox ?

### ISSUE THREAD

**Issue by sscotti** [HemantNegi/jquery.sumoselect#301]
I started to play around with this and found a way to capture the arrow key actions, but not sure how to set the selected index / option in that case.  The code below just uses the native select to get the total number of options and gets/sets the selectedindex based on the arrow keys, but not sure how to set the sumoselect option in that case ?  Just wondering if that is a feature in SumoSelect ?  Thanks

					$(".SumoSelect").on("keydown", function(e) {
					
						select = $(this).find(".SumoUnder");
						count = select.find("option").size();
						currentindex = select.prop('selectedIndex');
						handle = $(this)[0];
						console.log(handle);
						switch(e.which) {
						case 37: // left
						break;

						case 38: // up
						currentindex = Math.max(0, currentindex-1);
						console.log(currentindex);
						select.prop('selectedIndex', currentindex);
						break;

						case 39: // right
						break;

						case 40: // down
						currentindex = Math.min(count -1 , currentindex+1);
						console.log(currentindex);
						select.prop('selectedIndex', currentindex);
						break;

						default: return; // exit this handler for other keys
						}
						e.preventDefault(); // prevent the default action (scroll / move caret)
					
					});

**Comment by Zenoo** [comment]
Sumo already has key controls:

```js
          O.select.on('keydown.sumo', function (e) {
            switch (e.which) {
              case 38: // up
                O.nav(true);
                break;

              case 40: // down
                O.nav(false);
                break;

              case 65: // shortcut ctrl + a to select all and ctrl + shift + a to unselect all.
                if (O.is_multi && e.ctrlKey) {
                  O.toggSelAll(!e.shiftKey, 1);
                  break;
                }
                else
                  return;

              case 32: // space
                if (settings.search && O.ftxt.is(e.target)) return;
                break;
              case 13: // enter
                if (O.is_opened)
                  O.optDiv.find('ul li.sel').trigger('click');
                else
                  O.setOnOpen();
                break;
              case 9:	 //tab
                if (!settings.okCancelInMulti)
                  O.hideOpts();
                return;
              case 27: // esc
                if (settings.okCancelInMulti) O._cnbtn();
                O.hideOpts();
                return;

              default:
                return; // exit this handler for other keys
            }
            e.preventDefault(); // prevent the default action (scroll / move caret)
          });
```

**Comment by sscotti** [comment]
I see that.  However, that apparently is not activated when the "search" option is set to "true".  That must be by design.

**Comment by Zenoo** [comment]
It is, you can try it on the [Demo page](http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html).  
Is it not working for you?

**Comment by sscotti** [comment]
Must be some sort of conflict with another script somewhere.  

These are the settings that I'm using:

						placeholder: 'Select Here',
						csvDispCount: 0,
						captionFormat: '{2} Selected',
						floatWidth: 500,
						forceCustomRendering: false,
						nativeOnDevice: ['Android', 'BlackBerry', 'iPhone', 'iPad', 'iPod', 'Opera Mini', 'IEMobile', 'Silk'],
						outputAsCSV : false,
						csvSepChar : ',',
						okCancelInMulti: true,
						isClickAwayOk: false,
						triggerChangeCombined : true,
						selectAll : false,
						search : true,
						searchText : 'Search...',
						noMatch : 'No matches for "{0}"',
						prefix : '',
						locale :  ['OK', 'Cancel', 'Select All'],
						up : up,
						showTitle : false

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?

**Comment by sscotti** [comment]
https://codepen.io/stephen-d-scotti/pen/yLMwBog

**Comment by Zenoo** [comment]
This issue comes from your first disabled option.  
It works if you remove it.  
You can use a placeholder instead.

**Comment by sscotti** [comment]
Thanks.

**Comment by Zenoo** [comment]
The issue also seems to be solved as of the latest version.  
You can try keeping your disabled option with the latest version:  
```
https://gitcdn.link/repo/HemantNegi/jquery.sumoselect/v3.1.5/jquery.sumoselect.min.js
```

**Comment by sscotti** [comment]
That url resolves to:  https://gitcdn.link/cdn/HemantNegi/jquery.sumoselect/048729a1b88893c164359c15eec1e62474cf3579/jquery.sumoselect.min.js

There also seems to be an issue with initializing the script:  https://codepen.io/stephen-d-scotti/pen/yLMwBog

unless there is updated css to go along with that.

**Comment by Zenoo** [comment]
Yes, you should match the JS & CSS versions to 3.1.5

**Comment by sscotti** [comment]
Had to add .SumoUnder {opacity:1 !important} to get it to display correctly ?

https://codepen.io/stephen-d-scotti/pen/yLMwBog, with the latest distro.

**Comment by Zenoo** [comment]
You had the class `SumoUnder` on your base `<select>`. This class is used in the plugin and should not be used elsewhere.  
You should also use the same version for both CSS & JS: 

```html
<link rel="stylesheet" href="https://gitcdn.link/cdn/HemantNegi/jquery.sumoselect/048729a1b88893c164359c15eec1e62474cf3579/sumoselect.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script src="https://gitcdn.link/cdn/HemantNegi/jquery.sumoselect/048729a1b88893c164359c15eec1e62474cf3579/jquery.sumoselect.min.js"></script>
```

**Comment by sscotti** [comment]
OK, great, thanks.  It actually works with just the latest .zip from GitHub also.  Old code, but I guess I had a thing for country flags there also, which seems to still work.  Kind of performance hit though.

https://codepen.io/stephen-d-scotti/pen/yLMwBog
