### ISSUE TITLE
A weird problem: sumoselect change options by itself

### ISSUE THREAD

**Issue by zPz-002** [HemantNegi/jquery.sumoselect#302]
I use sumoselect with ajax to implement a cascade of three selectboxes in my django project ( Django==2.2 )
All things work well, but when I select the first selectbox and second selectbox like this
![image](https://user-images.githubusercontent.com/62230574/115358565-609c2180-a1f0-11eb-9b03-8a1d2a6c3a7c.png)
then , if I click the merge of the first selectbox(don't make the first selectbox's drop-down box down) to make the second selectbox's drop-down box closed like this
![image](https://user-images.githubusercontent.com/62230574/115359209-0bacdb00-a1f1-11eb-8a0c-5005ec8e1d46.png)
selected options in second selectbox will be cleared and selected options in first selectbox will also change to '水果'(means fruit) or '肉类'(means meat) (second selectbox's options change with the first selectbox's change, but first selectbox's show don't change ), like this
![image](https://user-images.githubusercontent.com/62230574/115360739-7dd1ef80-a1f2-11eb-8d4f-7434ff1b2ca7.png)
above picture shows that first selectbox's show don't change, but the selected options in second selectbox have been cleared
![image](https://user-images.githubusercontent.com/62230574/115360953-b07be800-a1f2-11eb-94d7-9ab6476c5c12.png)
above picture shows that second selectbox's options changed to just fruits(but I have selected '蔬菜'(means vegetables) and first selectbox shows right, so it's weird)
And it's even stranger that if I repeat the above operation, the second selectbox's option may change to just meats!
![image](https://user-images.githubusercontent.com/62230574/115361935-a4445a80-a1f3-11eb-9e6c-0f47344267e6.png)
 Then if I make all options in first selectbox unselected, there will show meats selected
![image](https://user-images.githubusercontent.com/62230574/115362392-1026c300-a1f4-11eb-846e-ea9d97ffdfa7.png)
The reason seems to be the childnode of Element $(".CaptionCont SelectBox") changed by itself
![image](https://user-images.githubusercontent.com/62230574/115362707-65fb6b00-a1f4-11eb-91fa-99d1796ea7ce.png)
But why it can change by itself? Is there anyone can help?

This is my jQury code of this part

```
$(document).ready(
    function select_option(){
        GetCategory_Big()
        $("#product-big-category").change(function (){
            GetCategory_Small()
            Get_Goods()
        });
        $("#product-small-category").change(function (){
            Get_Goods()
        });
    });

function GetCategory_Big(){
    var option_list = $("#product-big-category");
    option_list.empty();
    $.ajax({
        url:'/app/goods_info/',
        type:'POST',
        data:{
            'type': '0',
            "csrfmiddlewaretoken": $("[name = 'csrfmiddlewaretoken']").val()
        },
        success:function (data){
            $.each(data,function (i,item){
                $("<option></option>")
                    .val(item['category_b'])
                    .text(item['cb_name'])
                    .appendTo(option_list)
            });
            $("#product-big-category")[0].sumo.reload();
        }
    });
};
function GetCategory_Small(){
    var option_list = $("#product-small-category");
    option_list.empty();
    var cb_list=[];
    var i=0;
    $("#product-big-category option:selected").each(function (){
        cb_list[i]=$(this).val();
        i++;
    });
    $.ajax({
        url:"/app/goods_info_multi/",
        type:"POST",
        data:{
            'type':'1',
            'cb_list':cb_list,
            "csrfmiddlewaretoken": $("[name = 'csrfmiddlewaretoken']").val()
        },
        traditional:true,
        success:function (data) {
            $.each(data, function (i,item){
                $("<option></option>")
                    .val(item['category_s'])
                    .text(item['cs_name'])
                    .appendTo(option_list);
            });
            $("#product-small-category")[0].sumo.reload();
        }
    });
};

function Get_Goods(){
    var option_list = $("#product-name");
    option_list.empty();
    var cs_list=[];
    var i=0;
    $("#product-small-category option:selected").each(function (){
        cs_list[i]=$(this).val();
        i++;
    });
    $.ajax({
        url:"/app/goods_info_multi/",
        type:"POST",
        data:{
            'type':'2',
            'cs_list':cs_list,
            "csrfmiddlewaretoken": $("[name = 'csrfmiddlewaretoken']").val()
        },
        traditional: true,
        success:function (data) {
            $.each(data, function (i,item){
                $("<option></option>")
                    .val(item['goods_id'])
                    .text(item['goods_name'])
                    .appendTo(option_list);
            });
            $("#product-name")[0].sumo.reload();
        }
    });
};
```

**Comment by zPz-002** [comment]
When I test and shot screen, I change the selected option of the first selectbox carelessly.But it doesn't matter, because no matter what I select in first selectbox, it will happen the seem thing that I described.

**Comment by Zenoo** [comment]
@zPz-002 Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?
