### ISSUE TITLE
Multiple SumoSelects One below other ... Dropdown does not show for any apart from the first ...

### ISSUE THREAD

**Issue by 839998664** [HemantNegi/jquery.sumoselect#303]
I have a set of four SumoSelects one below the other. When I click the first one the Dropdown appears fine and am able to work with it. But when I click the second or any others below the Dropdown seems to hide underneath and cannot be seen. Not able to work with the selects apart from the first one. Looks like a Z-index issue...

![image](https://user-images.githubusercontent.com/6966807/119659842-36233100-be4c-11eb-96ba-e1f065ece783.png)

![image](https://user-images.githubusercontent.com/6966807/119659882-3fac9900-be4c-11eb-94c3-286b3496e76b.png)

![image](https://user-images.githubusercontent.com/6966807/119659918-4804d400-be4c-11eb-9afa-ce9e72cb4929.png)

**Comment by Zenoo** [comment]
@839998664 Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?
