### ISSUE TITLE
SumoSelect won't load in i.e. 11 / works in Chrome, Edge, Firefox

### ISSUE THREAD

**Issue by CharlieGMH** [HemantNegi/jquery.sumoselect#307]
SumoSelect v3.3.24;  jQuery v1.0.9 (same result on jQuery 3.6.0)

SCRIPT1002: Syntax error
jquery.sumoselect-3.3.24.js (22,9)
SCRIPT438: Object doesn't support property or method 'SumoSelect'
Foo.aspx (179,13) :

$(document).ready(function () {
     $('.programType').SumoSelect({
          placeholder: "All",
          captionFormatAllSelected: "All",
          selectAll: true,
          okCancelInMulti: true,
          isClickAwayOk: true
      });
});

Also, on SumoSelect Demo page:

sumoselect_demo.html
SCRIPT5007: Unable to get property '@@iterator' of undefined or null reference
jquery.sumoselect.min.js (1,1705)

I've tried several SumoSelect releases. Any guidance would be greatly appreciated!

**Comment by Zenoo** [comment]
I could reproduce the bug, I will try to solve it soon.

**Comment by Zenoo** [comment]
This should be fixed in [v3.3.25](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.25)

**Comment by CharlieGMH** [comment]
Better on the demo page, but it throws exceptions when selecting items:

```
sumoselect_demo.html
SCRIPT445: Object doesn't support this action
jquery.sumoselect.min.js (62,241)
```

On my page SumoSelect does look like it's getting initialized:

```
Login.aspx
SCRIPT1002: Syntax error
jquery.sumoselect-3.3.25.js (22,9)
HTML1300: Navigation occurred.
MYAPP
SEC7115: :visited and :link styles can only differ by color. Some styles were not applied to :visited.
MYAPP
SCRIPT1002: Syntax error
jquery.sumoselect-3.3.25.js (22,9)
jQuery.Deferred exception: 'ctl00_DefaultContentPlaceHolderCenter_lbProgramType' is undefined ReferenceError: 'ctl00_DefaultContentPlaceHolderCenter_lbProgramType' is undefined
   at Anonymous function (http://localhost/myapp/Foo.aspx:179:13)
   at mightThrow (http://localhost/myapp/Scripts/jquery-3.6.0.js:3766:10)
   at Anonymous function (http://localhost/myapp/Scripts/jquery-3.6.0.js:3834:12) undefined
SCRIPT5009: 'ctl00_DefaultContentPlaceHolderCenter_lbProgramType' is undefined
jquery-3.6.0.js (4059,3)
```
All still good on other browsers.

**Comment by Zenoo** [comment]
I can see this warning:
```
SCRIPT445: Object doesn't support this action
jquery.sumoselect.min.js (62,241)
```
But it doesn't prevent the plugin from working, I'll see what I can do about that.  
But for yoru error, could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?

**Comment by Zenoo** [comment]
The warning is fixed in [v3.3.26](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.26).

I think your other error comes from your script, but try to recreate the issue.

**Comment by kieran-ojakangas** [comment]
Hi @Zenoo

Unfortunately, this is occurring again in IE as of 3.3.0. Is there a possibility this can get addressed?

**Comment by Zenoo** [comment]
Hi, @kieran-ojakangas,  

Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?
