### ISSUE TITLE
Search on mobile

### ISSUE THREAD

**Issue by sightsciences** [HemantNegi/jquery.sumoselect#308]
Hello! 

I loooooooove sumoselect, truly!

However, search is not functioning on mobile (iphone / chrome / safari)

I have dug in and tried just about everything I can think of but I cannot get it to bring up the search on mobile - has anyone had this problem?

**Comment by Zenoo** [comment]
Did you try using the `forceCustomRendering` option?

**Comment by sightsciences** [comment]
<?php 
echo "<script type=\"text/javascript\">
$(document).ready(function () {
            $(\"[name='state']\").SumoSelect({
			search : true,
			triggerChangeCombined: true,
			forceCustomRendering: true			
			});
        });     
</script>"
;?>

This is currently my options - i've tried different options and no luck so far. On my iphone it just pulls up like a normal drop down and also has auto complete prompts - but no keyboard etc.

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?

**Comment by sightsciences** [comment]
I'll see what I can do - or you can look at our dev site that I am testing this stuff on : http://tearcare-stg.itwdev2.info/

**Comment by Zenoo** [comment]
Your website has errors before the sumoselect initialization: 
![](https://i.imgur.com/rteGALQ.png)

Please try to recreate the issue on a Codepen or JSFiddle, it'll be easier for me to fix the bug if there is one.

**Comment by sightsciences** [comment]
https://jsfiddle.net/xf8hdb6q/1/

Does that work? 

Our site was designed by another team and is on wordpress so there's a lot going on that I don't know much about - the behavior in that jsfiddle is same I get on my phone

**Comment by Zenoo** [comment]
Your fiddle didn't work, I created a JSBin instead, which works.
[Click here to test it on mobile](https://jsbin.com/vuxawet)
[Click here to see the code](https://jsbin.com/vuxawet/edit)
