### ISSUE TITLE
Plugin is not working with ui tabs correctly

### ISSUE THREAD

**Issue by apartamenti** [HemantNegi/jquery.sumoselect#31]
Hello,
Your plugin is amazing but there is  a bug. I am using with JQUERY UI tabs and when i click first tab everything is working well, until i am clicking second tab and regions are loading in the first tab. Should load to second tab.

screenshot from second tab
![screenshot_3](https://cloud.githubusercontent.com/assets/10740151/5936433/45b3b54a-a6ed-11e4-9a93-cfdb4e57fd61.jpg)
 
screenshot from first tab
![screenshot_4](https://cloud.githubusercontent.com/assets/10740151/5936452/7237f658-a6ed-11e4-8738-575ad558a037.jpg)

thank you very much,

**Comment by HemantNegi** [comment]
im unable to understand you problem, can you elaborate more clearly
may be with some live examples

Thanks

**Comment by apartamenti** [comment]
The problem marked fixed. Thank you for your interest!
