### ISSUE TITLE
Make it possible to deselect all by clicking "Select All" twice

### ISSUE THREAD

**Issue by ecobux** [HemantNegi/jquery.sumoselect#311]
[In the demo, Select All (without OK button),](https://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html) when you click "Select All" twice, none of the options are selected in the list - as expected. But when you then close the menu, the field shows again the previous selection. From that moment on the menu and the selected options are out of sync.

I also don't manage to select all items with "Select All". When I close the menu, the change is not visible.

Tested in Firefox and Chrome.

**Comment by Zenoo** [comment]
You must confuse the first test with the second.

![](https://i.imgur.com/CJseNw7.png)

To confirm the changes in the first test, you need to click `Ok`.  
You don't need to do it in the second.  

The difference is the `okCancelInMulti` prop.

**Comment by ecobux** [comment]
I'm talking about the second demo, without the OK button. Since there is no OK button I assume that it is sufficient to make a selection and then close the menu.

No matter if I select none or all options, there always remains "Ferrari".

![image](https://user-images.githubusercontent.com/1910838/128917992-f5df6adc-8def-44c9-8098-c57bd10d6896.png)
![image](https://user-images.githubusercontent.com/1910838/128918058-2308f8ac-f32a-4d7c-b05c-037f5da8a229.png)

**Comment by Zenoo** [comment]
Oh, I see what you mean. The items are selected, but the text in the placeholder doesn't change.  
Seems like it's a bug, I will try to fix it.

**Comment by Zenoo** [comment]
This should be fixed in [v3.3.28](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.28)
