### ISSUE TITLE
searchText not working

### ISSUE THREAD

**Issue by asrahi** [HemantNegi/jquery.sumoselect#312]
serchText option(placeholder) is not working
plz check~
Thank you!

![image](https://user-images.githubusercontent.com/5344149/131882451-5cbffd7c-2460-4ae9-9da6-6ba65dfacce0.png)

**Comment by Zenoo** [comment]
Thanks ! This should be fixed in [v3.3.29](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.29)
