### ISSUE TITLE
Delegated events broken since 17 june 2021?

### ISSUE THREAD

**Issue by d3stroyahh** [HemantNegi/jquery.sumoselect#316]
Hi,
since june 17th 2021 you can't trigger the change event in delegated events.
For instance 
$('body').on('change', '#sumoselect', function(){console.log('changed');}); not working
while
$('#sumoselect').on('change', function(){console.log('changed');}) works

now, I fixed the latest version by changing 
`callChange () {
          this.E.get().forEach(e => {
            dispatchEvent(e, 'change');
            dispatchEvent(e, 'click');
          });
        },`

to

`callChange () {
            this.E.trigger('change').trigger('click');
        },`

as it was in june 11th 2021.

Why was that change done? Maybe there was a reason I don't know

thanks

**Comment by d3stroyahh** [comment]
here it is

https://jsfiddle.net/x6su8jaw/

**Comment by Zenoo** [comment]
This should be fixed in [v3.3.30](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.3.30)
