### ISSUE TITLE
Control disappears when calling .reload() on mobile devices

### ISSUE THREAD

**Issue by merravid** [HemantNegi/jquery.sumoselect#318]
Test on mobile device (or use developer tools using mobile device size):
https://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html

In Live Actions section: Click on "Attach SumoSelect", followed by "Reload SumoSelet". Control will disappear.

This seems to be related to presence of "SelectClass" class on the 'p' element.

**Comment by Zenoo** [comment]
Thanks for the heads-up.  
Did you encounter this issue elsewhere?  
Or is it a demo page specific bug?

**Comment by merravid** [comment]
No, it's not only on the demo page. It was happening all over our implementation, then we discovered it also happened in the demo page.

**Comment by Zenoo** [comment]
This should be fixed in [v3.4.1](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.4.1)
