### ISSUE TITLE
Getting custom attributes from the selected option

### ISSUE THREAD

**Issue by calina-c** [HemantNegi/jquery.sumoselect#32]
A great feature on this would be having the possibility of getting attributes from the selected option, but since you can only get the selected option as value, that required ugly workarounds.

**Comment by HemantNegi** [comment]
You can anytime access the original select element and perform the necessary operations on its options.
The state of plugin is maintained by the underlying original select.

select the  underlying original select : `$('select.SlectBox')`
select all selected options :  `$('select.SlectBox option:selected')`

then you can perform all the DOM operations on these selected elements.
Cheers!!
