### ISSUE TITLE
Select all does not work in iPad 

### ISSUE THREAD

**Issue by najaabzlh** [HemantNegi/jquery.sumoselect#323]
Hi, I tested Sumo Select for 'Select All' but it does not working in iPad. In desktop there is no issue but when using the iPad it does not able to Select All. Can help on this ?

**Comment by Zenoo** [comment]
Which browser were you using at the time?

**Comment by najaabzlh** [comment]
> Which browser were you using at the time?

I am using Safari

**Comment by Zenoo** [comment]
This seems to be a bug specific to Safari.  
I am unable to debug this on Safari at this time, if anyone is interested in fixing it, a PR would be most welcome!

**Comment by waema** [comment]
It also doesn't work on android. On pc same code is working. for version 3.0.2 of the code it doesn't have this issue.

**Comment by Zenoo** [comment]
@waema Did you make sure to enable the `forceCustomRendering` option?  
On mobile, the native select is used instead of the custom one by default.

**Comment by waema** [comment]
@Zenoo yes it is enabled. My test was on the latest version 3.4.5.

**Comment by Zenoo** [comment]
@najaabzlh @waema I think I found the issue.  
The `:hidden` selector wasn't behaving the same way on desktop or mobile.  

This should be fixed in [v3.4.6](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.4.6)
