### ISSUE TITLE
SumoUnder class

### ISSUE THREAD

**Issue by alek101** [HemantNegi/jquery.sumoselect#325]
Hello,

It is necessary to add z-index: -1 or lower number to resolve a bug. With only opacity 0, it is stile possible to click on underline select box and to activate option that was not intended. 

All best

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?

**Comment by alek101** [comment]
Not really, but today I fixed bug by doing just that, on quite large project. Clicking under the box did select options, and we could see that because we are having another function that prints results underneath it. When I unchecked the opacity, I could clearly see html element.

**Comment by Zenoo** [comment]
I can't seem to reproduce your bug on my end, There is nothing under the option menu for me.  
It would really help if you could reproduce this bug in a simple environment so I could take a closer look at it.  

Which browser and OS are you using?

**Comment by alek101** [comment]
I wish I could reproduce them, but this issue helped me to fix my bug is 141.
It was Chrome and Firefox, on windows 2012R2 server, as part of massive project in CFWHEEL framework, that also using bootstrap. Dozens of js and css files are included.
