### ISSUE TITLE
Server side option rendering

### ISSUE THREAD

**Issue by KrishDunn** [HemantNegi/jquery.sumoselect#326]
I am developing my application in .net MVC.
I need to load more than a thousand options in the multi-select option. it takes a while to load data.
is there any server-side render option? like typeahead functionality to load data.

**Comment by Zenoo** [comment]
There is no "autocomplete" feature yet.  
In the meantime, if you have enable the search option on your select, you could listen to the `input` event of the search input `#yourSelect + .SelectBox input.search-txt`, and update your options from that.
