### ISSUE TITLE
Select UnSelect MultiSelect DropDown Using Jquery , All DropDown Depend on Previews Dropdown 

### ISSUE THREAD

**Issue by ZeeshanRS** [HemantNegi/jquery.sumoselect#327]
hello Buddy , i have a Issue , when i was loaded the 2nd MultiSelect Dropdown Using Jquery , Select All working in all browser but in Mozila FireFox its not working
image
![image](https://user-images.githubusercontent.com/102017817/169759757-9b86e0b6-c9ad-4082-9769-f9f0c5e867e7.png)

look at this its chrome working perfect but in 2nd image check my serious issue
image

its Mozila FireFox
![image](https://user-images.githubusercontent.com/102017817/169759707-ad67f3a2-321f-4f1e-b5ef-a428f941ac6c.png)

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?

**Comment by ZeeshanRS** [comment]
sure

**Comment by ZeeshanRS** [comment]
![image](https://user-images.githubusercontent.com/102017817/170192220-8d53e0df-c802-4f34-9b2f-6fec6382ca0b.png)


this is console Error

**Comment by ZeeshanRS** [comment]
![image](https://user-images.githubusercontent.com/102017817/170192370-eb100fb3-2d1e-4120-ac3c-db2206effab4.png)

**Comment by ZeeshanRS** [comment]
its only accure in Mozila

**Comment by Zenoo** [comment]
I need to be able to see the issue on a working example to be able to see what the problem is.  
Can you please go to https://jsfiddle.net/, recreate a minimal example showing the issue and send me the link to your example?
