### ISSUE TITLE
TypeError: settings.nativeOnDevice[i].toLowerCase is not a function

### ISSUE THREAD

**Issue by davorgit** [HemantNegi/jquery.sumoselect#33]
got this error when using jquery no-conflict with mootools
the problem is on line 310

this is because mootools implements its own methods and other stuff in js I think
one solution is to never use for-var-in loop, and use regular for loop instead 
or other solution is to check with typeof == 'string' in for-var-in loop in this case

this is the console.log(settings.nativeOnDevice[i]); result from this loop:
Android
BlackBerry
iPhone
iPad
iPod
Opera Mini
IEMobile
Silk
function()
Array()
function(t, e)
function()
function()
function(t)
function(t)
function(t)
function(t, e)

happens like I said on line 310 
if (ua.toLowerCase().indexOf(settings.nativeOnDevice[i].toLowerCase())

**Comment by davorgit** [comment]
here you go this is fixed line 310 with no errors after replacing it ;)

```javascript
for (var i = 0; i < settings.nativeOnDevice.length; i++) if (ua.toLowerCase().indexOf(settings.nativeOnDevice[i].toLowerCase()) > 0) return settings.nativeOnDevice[i];
```

**Comment by HemantNegi** [comment]
Thanks buddy
added the fix.
Cheers!
