### ISSUE TITLE
Bug with example okCancelInMulti: true & triggerChangeCombined: false

### ISSUE THREAD

**Issue by AzzaAzza69** [HemantNegi/jquery.sumoselect#331]
Steps to reproduce:
* go to the list example page
* scroll down to Other examples (specifically the okCancelInMulti: true, triggerChangeCombined: false)
* click on select to drop it down
* tick/untick an option
* press Cancel

outcome:
* Doesn't revert select text back to what it was (but if you re-click the select you see that the dropdown tick list has)

This doesn't happen on the next example so it may be something to do with triggerChangeCombined: true/false....

**Comment by Zenoo** [comment]
Thanks for pointing it out.  
I will look into it later today.

**Comment by Zenoo** [comment]
This should be fixed in [v3.4.7](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.4.7)
