### ISSUE TITLE
Links (anchors) do not work in android (mobile)

### ISSUE THREAD

**Issue by onedaybefore** [HemantNegi/jquery.sumoselect#332]
Hello!
I use the search drop-down list (sumoselect v3.4.8), but in `const li = $(<li class="opt">` I added `<a href="#${opt.val()}">` so that the list items are anchored links and the link is formed from "value". This works and when you click, the link redirects to the desired section, it also works when I open the site from the browser, but change the permission for my mobile phone.

But in the phone itself, for an unknown reason, the links stop working, while the anchors work separately. Obviously, the problem is sumoselect, I do not understand why the mobile version does not work, initially it did not want to open at all, but I put `forceCustomRendering: true` after which the list earned, but does not follow the link.

I tried to use android emulators to understand the cause of the error, but in emulators the links work, in the mobile browser chrome on android for some reason the links stop working.

Please help me to know how to make links work in a mobile browser?

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?

**Comment by onedaybefore** [comment]
You can see live here: https://kazguu.tecre.kz/international-cooperation/global-network

**Comment by onedaybefore** [comment]
Strange, I created a project in codepen (https://codepen.io/Daniyar01/pen/mdxzRvG), but in codepen the links work. Can you tell me why this does not work on my website only in a mobile browser via phone?

**Comment by Zenoo** [comment]
You might have other code interfering with this library.  
Everything seems fine on my end

**Comment by onedaybefore** [comment]
I can't check the code because opening devtools on the mobile version works. But when I open from the phone, the links stop working. And through the phone I don't know how to work with code

**Comment by onedaybefore** [comment]
Did you check through the phone? Do you have anchor transitions on the site?
