### ISSUE TITLE
Improve compatibility with a regular SELECT by handling specific mouse/keyboard

### ISSUE THREAD

**Issue by AzzaAzza69** [HemantNegi/jquery.sumoselect#333]
Specifically:
* keyboard : Page Up, Page Down, Home and End usually navigate the items in the list (when the control is focused) and don't bubble back up to the page. If search:true, the Home and End keys would instead be Ctrl+Home and Ctrl+End so as to not interfere with the input keys.
* mouse: scrolling via the wheel (while over the dropped list) should never bubble backup up to the page. Using the optgroup example on the demo page, it would appear this is happening when the list can't be scrolled anymore (either up or down).

**Comment by Zenoo** [comment]
You can already navigate the options with the arrow keys.

The scrolling is the default browser behavior.

**Comment by AzzaAzza69** [comment]
I completely agree, that a browser's default behaviour is to scroll but I was suggesting to improve the user experience and perform more like a usual select does (as it DOES NOT scroll the page).
Regarding Page Up/Down... if you have several pages of options, surely page down 3 times would be better than pressing cursor down 40 times (or holding the key down).
PS. Other libraries like Select2 stop the scrolling so it is possible.
