### ISSUE TITLE
Possible enhancement: after a mouse click, set the item to have the .sel class

### ISSUE THREAD

**Issue by AzzaAzza69** [HemantNegi/jquery.sumoselect#334]
so the user will know the next item to be selected after a subsequent cursor up/down would be the one above/below the just selected.

To emulate the SELECT behaviour, the item would have .sel on mouseover but as a SELECT doesn't handle staying open after a click, I think doing it after a click would be ok...

**Comment by Zenoo** [comment]
Could you please give me an example of this enhancement ? I didn't quite catch your explanation.

**Comment by AzzaAzza69** [comment]
a long list, cursor down so first option is selected, use the mouse wheel to scroll down the list, hover over an option (it highlights).  If I press cursor down, the list shoots back to the top and selects the second option...

**Comment by Zenoo** [comment]
I don't understand, why should the list shoot back up to the top after you select an option?  
The hovered styles are already applied, take a look at the 3rd search demo for the scrolling behavior.

**Comment by Zenoo** [comment]
This is a non-issue for me.  
The item selected via the arrows, has a blue highlight, where as the item hovered by mouse has a grey highlight.

They are 2 different focuses.

![](https://i.imgur.com/95gBYov.png)
