### ISSUE TITLE
Option to save selection to local storage

### ISSUE THREAD

**Issue by ChristianGrieger** [HemantNegi/jquery.sumoselect#336]
Is there a way to save the selection to local storage and reload it after page load?

**Comment by Zenoo** [comment]
You can simply store the selection in the localStorage yourself,check it on page load, and load sumoselect with these options selected. This is already possible.

**Comment by ChristianGrieger** [comment]
Okay, will try that :) thank you. What option do i need to use to load the selected?

**Comment by Zenoo** [comment]
Simply call `.sumoselect` on your select with your options already selected
