### ISSUE TITLE
Usability improvement: Scroll (first) selected into view when dropping list down...

### ISSUE THREAD

**Issue by AzzaAzza69** [HemantNegi/jquery.sumoselect#337]
On dropdown, it should bring the (first) selected into view or the first item in the list if nothing selected - it currently leaves the list where you last scrolled it to.

**Comment by Zenoo** [comment]
This should be fixed in [v3.4.9](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.4.9)
