### ISSUE TITLE
Bug + Fix: Search box doesn't handle changes actioned via context menu...

### ISSUE THREAD

**Issue by AzzaAzza69** [HemantNegi/jquery.sumoselect#339]
As Sumo uses the on('keyup') event to detect text changes in search box, it doesn't handle cut & paste via right-click context menu.

Suggested fixes:
In Search(), I changed the on('keyup.sumo'... to on('input.sumo'...
In HideOpts(), I changed the trigger('keyup.sumo'); to trigger('input.sumo');

**Comment by Zenoo** [comment]
This should be fixed in [v3.4.9](https://github.com/HemantNegi/jquery.sumoselect/releases/tag/v3.4.9)
