### ISSUE TITLE
Enhancement + Fix: If the original 'hidden' select ever gets focus, focus the sumo one instead

### ISSUE THREAD

**Issue by AzzaAzza69** [HemantNegi/jquery.sumoselect#342]
Suggested fixes:
in basicEvents(), I added:

O.E.on('focus', (e) => {
  O.select.focus();
});

**Comment by Zenoo** [comment]
Could you reproduce a case where the original select gets focused?

**Comment by AzzaAzza69** [comment]
Yeah...
````$('#combobox').focus()
````
it's a safety measure...if someone has a project already written and they want to use sumo...if they have any "set focus" code or "autofocus" left in, it will still "work"...

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?
