### ISSUE TITLE
Selected values not displaying in Firefox

### ISSUE THREAD

**Issue by vanboom** [HemantNegi/jquery.sumoselect#345]
In a multi-select, the text of two or more selected items is showing as ", , ," in the select box. 

This line: 
https://github.com/HemantNegi/jquery.sumoselect/blob/08cb78ba383f8e7dd659588c7fa102096dbc1181/jquery.sumoselect.js#L642

Replacing `selected.innerText` with `selected.textcontent` resolves the issue.  Lmk if you prefer a PR...I'm hoping you can roll this simple one into the master branch without a PR.   Thanks!

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?

As I understand it, the problem most likely lies in your implementation.
See [this link](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent#differences_from_innertext) for more info about `innerText` and `textContent`
