### ISSUE TITLE
UnSelectAll() Does Not Clear Selected Options UI

### ISSUE THREAD

**Issue by tanayshah0908** [HemantNegi/jquery.sumoselect#346]
Hi, 

When using unSelectAll(), it clears the selected options from model and text box but when I reopen the dropdown, the options are still selected, i.e., have the checkbox checked. Is there anything additional I need to do to unselect all options when reseting a form?

Thanks in advance.

**Comment by Zenoo** [comment]
Could you please try to recreate the issue on a Codepen or JSFiddle and send me the link?  
I just tested it and it clears the checkboxes too
