### ISSUE TITLE
Automatic up/down instead of static

### ISSUE THREAD

**Issue by mario0511** [HemantNegi/jquery.sumoselect#351]
Hi there :)
Unfortunately the script does not detect that the dropdown menu is outside of the page.
In our case, where the select sits at the bottom of the page, the dropdown menu is outside of the visible range.
Is there a way to change this behaviour?

**Comment by Zenoo** [comment]
You can use the `up` option to force it opening up towards the top.

**Comment by mario0511** [comment]
What can i do if the dropdown is not on the bottom but it gets opened near window bottom?
In this case the user is forced to scroll up to interact with the dropdown.

Shouldnt it automatically detect if the dropdown exceeds the visible range?

**Comment by Zenoo** [comment]
There is no automatic up/down detection for now, unfortunately.
Using the native dropdown should work for you, but you will loose on other features.
