### ISSUE TITLE
Bug: Can't use options okCancelInMulti and ClearAll at the same time

### ISSUE THREAD

**Issue by aj-potc** [HemantNegi/jquery.sumoselect#353]
When using options `okCancelInMulti` and `ClearAll`, the "Clear All" link is not active, and clicking it will not remove the selection.

Here are the options as used to apply to a new select box:
`$('.multi-clean-close').SumoSelect({okCancelInMulti: true, clearAll: true});`

See the following JSFiddle for an example:

https://jsfiddle.net/1h0c8qLm/2/

Is anyone aware of a workaround to enable the OK/Cancel buttons, while also supporting the Clear All feature?

Thanks very much.

**Comment by Zenoo** [comment]
The `Clear All` button only clears truly selected options.
Having `okCancelInMulti` enabled means you have to validate your changes by clicking on `Ok` before they are applied.
`Clear all` won't work until you have validated your changes.
