### ISSUE TITLE
New Feature: the ability for users to add their own options

### ISSUE THREAD

**Issue by anthonylebrun** [HemantNegi/jquery.sumoselect#36]
Really awesome plugin you have here @HemantNegi. One UI feature that I get a lot from clients is the ability for users to be able to create their own option if it's not pre-populated in the multiselect (think the "other" field in questionnaires).

I'll submit a pull request as soon as I have a bit of time to work on it, but wanted to find out if anyone else would find this helpful.

**Comment by HemantNegi** [comment]
Yup i was thinking of that,
Please make it on development branch as master is not upto date.

Cheers!!

**Comment by HemantNegi** [comment]
Hey 
did you tried `.add(value [,text][,index])` method i guess this is what you are looking for.
Regards
