### ISSUE TITLE
A few items..

### ISSUE THREAD

**Issue by samcov** [HemantNegi/jquery.sumoselect#45]
I really like what you've done here, and here are a few things that I couldn't find, or hopefully you may add.

1. I couldn't find a way to manipulate the underlying select and then have the sumo select refresh its state. This would be nice, but if the other things are done, it's not absolutely required. You already update the select when items are added, which greatly simplifies my adoption!

2. How do you remove ALL of the items. In a select, you just set the options length to 0.

3. How do you clear all of the checked items in a multiselect? I believe that in a select, you just set the selected index to -1, however sumo dies if I do that!

4. How do you set the height of the dropdown if possible?

Great Control, Thanks!

**Comment by HemantNegi** [comment]
Will try to overcome these in next release.

Thanks!

**Comment by samcov** [comment]
Thanks, that's all we can ask!!!

**Comment by HemantNegi** [comment]
To  access the underlying select you can simply select it via jquery
`$('select.SlectBox')[0];`
or alternatively
`$('select.SlectBox')[0].sumo.E`
then to update the sumoselect UI you can use 
`$('select.SlectBox')[0].sumo.reload();`

You can always perform the required operations on underlying select and then update the UI

To Uncheck all items
`$('select.SlectBox')[0].sumo.unSelectAll();`

The height of control is set through css, simply override this class
`.SumoSelect > .optWrapper > .options{max-height: 250px}`
and set `max-height` property

**Comment by samcov** [comment]
Very Good!!!
