### ISSUE TITLE
One Request

### ISSUE THREAD

**Issue by samcov** [HemantNegi/jquery.sumoselect#46]
Is it possible to have the drop down stay opened at a fixed height, like a listbox?

**Comment by samcov** [comment]
**Update**: I added a keepOptionsOpen member, that if true, I return from the hide options method.

On ready, I call the showOpts method, and set the keepOptionsOpen  parameter to true for selected dropdowns, and it works fine.

However, I suspect that you may want to do it another way, and likely hide the down arrow of the control.

**Comment by HemantNegi** [comment]
For this i think you can play with css:
`.SumoSelect > .optWrapper {
visibility: visible !important;
opacity: 1 !important;
position: static  !important;;
}
.SumoSelect > .CaptionCont { 
    display:none; 
}`
