### ISSUE TITLE
Error in ipad

### ISSUE THREAD

**Issue by SrilalithaAdiraju** [HemantNegi/jquery.sumoselect#48]
I am getting the following error in ipad 
Error : 
TypeError: 'undefined' is not an object (evaluating 'O.E.find('option[value="'+li.attr("data-val")+'"]')[0].selected=li.hasClass("selected")') 

When I select any option the error is
Unable to set value of the property 'selected': object is null or undefined

**Comment by HemantNegi** [comment]
Hi,
i dont understand why this is happening can you, provide more details like ios version, browser.
and what configuration settings are you using.

**Comment by HemantNegi** [comment]
Closing this for now
