### ISSUE TITLE
Custom color for each individual option

### ISSUE THREAD

**Issue by stig22** [HemantNegi/jquery.sumoselect#49]
Is it possible to set a different text color for each option within a sumoselect control?

I tried the following but did not seem to take effect: (text color still black)
   
    -  $("#sumoselectControl option")[aryOptionListIndex].style.color = "#FF00CC"

    -  $.each(aryOptionList, function (key, value) {
                $('#sumoselectControl')
                    .append($("<option style='color:#FF00CC;'></option>")
                    .attr("value", value)
                    .text(value))
            });

Any ideas?

Thanks!!
Steve

**Comment by HemantNegi** [comment]
Yup
Now the classes added to options are added to corresponding li in the control.

Regards
