### ISSUE TITLE
Multiselect - onsubmit - no get or post value

### ISSUE THREAD

**Issue by wasay** [HemantNegi/jquery.sumoselect#51]
Hi,
I am running into an issue with form submission for multiple select.

To recreate issue:

//select
name = my_select[]
multiple = multiple
class = SlectBox

//js
$('.SlectBox').SumoSelect({okCancelInMulti:true, selectAll:true });

//form
action = get

//user action
select only one item and submit the form

The single option is not reported on submission. 
On multiple selection, the last item is not reported on submission.

**Comment by HemantNegi** [comment]
Can you put it on fiddle, as i cant replicate the issue.

Thanks

**Comment by badrusalsyihab** [comment]
hi HemantNegi,

can you give me example for submission  or post selected to db

thanks

**Comment by HemantNegi** [comment]
it gets posted like normal select.

However here is an example.
```<form method="get" ><p>
    <select name="somename" multiple class="SlectBox">
        <option  value="volvo">Volvo</option>
        <option  value="saab">Saab</option>
        <option  value="mercedes">Mercedes</option>
        <option  value="audi">Audi</option>
        <option value="ritz">Ritz</option>
        <option  value="maruti">Maruti</option>
        <option value="skoda">Skoda</option>
        <option value="vlokswagen">Volkswagen</option>
        <option value="chevrolet">Chevrolet</option>
        <option  value="renault">Renault</option>
        <option  value="suzuki">Suzuki</option>
        <option  value="parsart">parsart</option>
    </select>
</p>
<input type="submit" value="SUBMIT">
</form>```

**Comment by badrusalsyihab** [comment]
Hi HermanNegi..

Thanks for your answer.
now My problem Solved

Thanks..

On Fri, Apr 17, 2015 at 12:27 PM, Hemant Negi <notifications@github.com>
wrote:

> it gets posted like normal select.
>
> However here is an example.
> <form method="get" ><p>
> <select name="somename" multiple class="SlectBox">
> <option value="volvo">Volvo</option>
> <option value="saab">Saab</option>
> <option value="mercedes">Mercedes</option>
> <option value="audi">Audi</option>
> <option value="ritz">Ritz</option>
> <option value="maruti">Maruti</option>
> <option value="skoda">Skoda</option>
> <option value="vlokswagen">Volkswagen</option>
> <option value="chevrolet">Chevrolet</option>
> <option value="renault">Renault</option>
> <option value="suzuki">Suzuki</option>
> <option value="parsart">parsart</option>
> </select>
> </p>
> <input type="submit" value="SUBMIT">
> </form>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HemantNegi/jquery.sumoselect/issues/51#issuecomment-93895969>
> .
>



-- 
*Regards,*
Badrus Sholeh

Telp :088210990983
Email :badrusalsyihab@gmail.com
Website :badrus.16mb.com

**Comment by krathodfulcrum** [comment]
> Hi HermanNegi..
> 
> Thanks for your answer.
> now My problem Solved
> 
> Thanks..
> 
> On Fri, Apr 17, 2015 at 12:27 PM, Hemant Negi [notifications@github.com](mailto:notifications@github.com)
> wrote:
> 
> > it gets posted like normal select.
> > However here is an example.
> > 
> > 
> > Volvo
> > Saab
> > Mercedes
> > Audi
> > Ritz
> > Maruti
> > Skoda
> > Volkswagen
> > Chevrolet
> > Renault
> > Suzuki
> > parsart
> > 
> > 
> > 
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > [#51 (comment)](https://github.com/HemantNegi/jquery.sumoselect/issues/51#issuecomment-93895969)
> > .
> 
> _Regards,_
> Badrus Sholeh
> 
> Telp :088210990983
> Email :[badrusalsyihab@gmail.com](mailto:badrusalsyihab@gmail.com)
> Website :badrus.16mb.com

How did you fix this issue, I also getting the last value :(
