### ISSUE TITLE
_cnbtn is called on outside click?

### ISSUE THREAD

**Issue by hi-tech** [HemantNegi/jquery.sumoselect#52]
Nice plugin :+1: 

Ran into an `outside click` issue with a multi-select, a select all, and no `Ok / Cancel` buttons. If the user clicked outside after making their selections, the selected options are cleared.

Traced it back to this line:
[`if (O.is_multi && settings.selectAll)O._cnbtn();`](https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js#L242)

Why is the `O._cnbtn()` function called here? Removing that call fixes this issue. Otherwise, the user must actually click on the `CaptionCont` to save the selections - which will not be obvious. Most users simply slick outside of a select to dismiss it, not click on the select again (even with the `Ok / Cancel`)

---

Edit: On 2nd thought, maybe this should be made on option as I do see it being useful in both use cases

Thanks.

**Comment by HemantNegi** [comment]
Thanks for bringing it to notice.

Will fix it.

**Comment by HemantNegi** [comment]
Hey,

I have drafted a new release can you confirm the fix.
 
Thanks

**Comment by hi-tech** [comment]
Fix confirmed, no longer an issue, thanks for the quick fix...

**Comment by HemantNegi** [comment]
Great !!
