### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by r-flash** [HemantNegi/jquery.sumoselect#55]
When the selectbox is on the bottom of an element with `overflow: hidden;`, it gets cropped and some of the options are unreachable for the user. Could you provide some way of setting a container element, so that the select box opens above the input in case it would colide with the containers bottom?

**Comment by HemantNegi** [comment]
Hi,
Can you provide a fiddle for the problem

**Comment by r-flash** [comment]
I'm sorry for the delay. Here is the fiddle https://jsfiddle.net/hd8zwu3q/ .
I realize that I'm explicitly setting overflow hidden, but it would be nice if the plugin could determine if there is enough space above the select, and if so, display it there instead of letting it clip.

**Comment by HemantNegi** [comment]
ok,
will figure out workarounds for the problem.

Thanks

**Comment by supermarcos** [comment]
Any luck with this issue?
Thanks

**Comment by michaelalhilly** [comment]
The only way that comes to mind is creating a duplicate select element outside the container and hiding it offcanvas and displaying it in place when the original select is clicked. You also have to update the original select value to the duplicates value.

**Comment by HemantNegi** [comment]
Not easy to do this, However by reading this http://stackoverflow.com/questions/15438828/extending-position-absolute-div-outside-overflow-hidden-div
i am able to male it usable inside a container having `overflow: hidden `

[https://github.com/HemantNegi/jquery.sumoselect/blob/master/select_responsive.html](https://github.com/HemantNegi/jquery.sumoselect/blob/master/select_responsive.html)
