### ISSUE TITLE
Selected Size problem

### ISSUE THREAD

**Issue by samcov** [HemantNegi/jquery.sumoselect#56]
When using the control in the mode where the all of the items are shown, the selected item view port is not displayed properly, there is some clipping... see attached picture.
![sumo](https://cloud.githubusercontent.com/assets/1551314/7217459/20102408-e5e1-11e4-8791-d26672d7816c.jpg)

**Comment by HemantNegi** [comment]
Its seems a css issue.
Try the latest sumoselect.css from repository.
or put it on a fiddle.

Thanks

**Comment by samcov** [comment]
That corrected the problem... Thanks!
