### ISSUE TITLE
Internet Explorer 11: Item selection doesn't work

### ISSUE THREAD

**Issue by Stopperharley** [HemantNegi/jquery.sumoselect#57]
When I use Internet Explorer 11 to use the Sumoselect control white multiple selection, I cannot select an item from the dropdown menu. When the page is loaded I click on dropdown button, the menu appears. When I click in the flyout menu the menu disappears whithout selecting any item.

Confusingly sometimes the clicked item gets selected when I open the menu and wait for a while before clicking an item.

The Javascript console doesn't show any messages like errors. In other browsers (tested with chrome, firefox and opera) the same page works fine. The problem also appears on your demo page with Internet Explorer 11.

![image](https://cloud.githubusercontent.com/assets/12063150/7269294/f1eed1d8-e8d2-11e4-9b69-c62a9b10d756.png)
![image](https://cloud.githubusercontent.com/assets/12063150/7269304/085e6a5a-e8d3-11e4-9499-74777d4b4fa8.png)

**Comment by phbou72** [comment]
Got the same problem with IE 10 too.

**Comment by HemantNegi** [comment]
Hey 
I know there are some issues with internet explorer.

can you check using the latest dev version from here https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js

also can you explain me the exact nature of problem.

Thanks

**Comment by Stopperharley** [comment]
Hi
I've already checked the latest dev version. And unfortunatly the problem also appears in this version. 

The problem is, that IE calls blur or focusout when clicking the flyout menu. Other browsers like FF or Chrome don't.

O.select.on('blur focusout', function () {
                        if(!O.is_opened)return;
                        //O.hideOpts();
                        O.hideOpts();

So by clicking any point in the flyout, it gets closed before selecting any option.

Could you please fix that problem? Thank you very much!!!

**Comment by HemantNegi** [comment]
Thanks for detailed feedback,
 I will look for alternative solutions.

**Comment by HemantNegi** [comment]
@Stopperharley  I have made some changes to close the dropdown, and its working fine in my version of ie(11). can you confirm on your end.
https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js

**Comment by Stopperharley** [comment]
Works perfect with my IE11 and my test pages. 

Thanks a lot for the quick solution!!!

**Comment by HemantNegi** [comment]
Ok Thats great,
Then i'm drafting a new release.

Thanks for support!
