### ISSUE TITLE
Client side validation

### ISSUE THREAD

**Issue by sanurocks** [HemantNegi/jquery.sumoselect#58]
Does the plugin not carry forward the required attribute from the html select or am I missing something. And that being the case, If we want to manually apply required attribute which element would it be? It is necessary for client side validation.

**Comment by HemantNegi** [comment]
Currently it does not provide any validation support,
however i have used jquery validation with this.
here is a reference : http://www.bidnbid.com/accounts/signup/?seller

**Comment by sanurocks** [comment]
Ok. I saw the source code for the page and the script, You are using the class selector for providing validation. I was able to validate the page using some different code, I just wanted to know if the plugin does it automatically or not. Thanks

**Comment by sanurocks** [comment]
For anyone viewing this after being closed. You can see the answer as per plugin owner. Or you can use my method by changing the jquery validator settings as per your needs.

**Comment by MswathiM** [comment]
> Currently it does not provide any validation support,
> however i have used jquery validation with this.
> here is a reference : http://www.bidnbid.com/accounts/signup/?seller

The above provided link is not available now. Can you please share the correct link to refer this?
