### ISSUE TITLE
optgroup style

### ISSUE THREAD

**Issue by Gouigouix** [HemantNegi/jquery.sumoselect#59]
Hi Hemant,

is it be possible to have a style for "optgroup"? With or without multiselect!

Best job,
John.

**Comment by HemantNegi** [comment]
Hi @Gouigouix ,

Currently the optgroup feature is not supported in plugin,
but here is a workaround you can use to achieve the similar visual effect.
http://jsfiddle.net/HemantNegi/Lyoc4n5k/2/

Regards!

**Comment by Gouigouix** [comment]
Thank you @HemantNegi

**Comment by CSergienko** [comment]
I couldn't get away from using actual optgroups, so I had to monkey-patch together my own solution:
http://codepen.io/TheOneWhoDid/pen/QbGJLE

Did it by creating a new function specifically for handling optgroups, so very little else has changed in the rest of the plugin's code.

When an optgroup's option is selected, the placeholder becomes 'Optgroup Label - Option Text'.

Hasn't been tested with multiple selects, as I don't use those in my project.

**Comment by Adyyda** [comment]
Hello CSergienko. In your demo, subcategories are joined and so they can't be selected individual. Any fix for this? Thanks
![1](https://cloud.githubusercontent.com/assets/5921012/11021066/7dcc1bb2-863e-11e5-9566-586149935e42.jpg)

**Comment by CSergienko** [comment]
@Adyyda The optgroup has to have the label attribute, I think, and it appears that is what you are missing. Just to be clear, I'm not a contributor, so that demo is literally a hack to get it to work for my specific use case. You may have to expand on the hack to make it work as you need it, until there's a proper solution.

**Comment by Adyyda** [comment]
Hello again. Can you tell me how i can show instead "Optgroup Label - Option Text'" just "Option Text'"?
I need to lose this because in a area that does not have optgoup the dropdown is fine, showing just the name of subcategory and in another with optgroup it shows different. So i have to show them in the same way. Thanks

**Comment by Adyyda** [comment]
got it...
changed O.placeholder = O.E.find(':selected').parent('optgroup').attr('label') + ' - ' + O.E.find(':selected').not(':disabled').text();

into 

O.placeholder = O.E.find(':selected').not(':disabled').text();

**Comment by aniketng876** [comment]
How can I add check-box for OptGroup and on selection of it, its all child options will get selected and deselected ??

**Comment by aniketng876** [comment]
Or else how can we dynamically add optgroup using jquery?

**Comment by HemantNegi** [comment]
SumoSelect now supports Optgroups.
To add optgroups dynamically you can add them to underlying select select element and then reload the plugin using `.reload()` method

**Comment by aniketng876** [comment]
http://livemysite.com/Eduardo/index.php

**Comment by aniketng876** [comment]
sumo.add(data[i].id, data[i].name);

**Comment by HemantNegi** [comment]
Currently there is no method to add optgroup. the only way is to update underlying select and then reload the plugin

**Comment by aniketng876** [comment]
can we replace html and reload the plugin. will it work??

**Comment by aniketng876** [comment]
$('#select_zone').html('');
$('#select_zone').html('
<optgroup label="ZONE 1" class="group-1">
                            <option value="Zonea 1">Zonea-1</option>
                            <option value="Zonea 2">Zonea-2</option>
                        </optgroup>  
                        <optgroup label="ZONE 2" class="group-2">
                            <option value="Zonea 3">Zonea-3</option>
                            <option value="Zonea 4">Zonea-4</option>
                        </optgroup> ');
$('#select_zone')[0].sumo.reload();

**Comment by HemantNegi** [comment]
Yes this will work

**Comment by aniketng876** [comment]
Ok thanks. worked. 
Now i want to add selection for Parent node and on selection of it, select its sub-nodes.

**Comment by HemantNegi** [comment]
We will work on this in next release

**Comment by aniketng876** [comment]
Hi, i done that with help of jquery.
But getting problem while reloading sumoselect element.
getting following error.
Uncaught TypeError: Cannot read property 'reload' of undefined

same error is there on this demo link
http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html

**Comment by omar-imran** [comment]
@HemantNegi Hi, does the plugin support OptGroup checkbox now? i need to add multi-groups inside one list and be able to select full group items at once.
![optgroup](https://user-images.githubusercontent.com/10810853/40423937-b39752a0-5e9c-11e8-9c72-88ec6dca5bf3.jpg)
