### ISSUE TITLE
fix doc

### ISSUE THREAD

**Issue by thoka** [HemantNegi/jquery.sumoselect#60]
$('select.SlectBox')[0].sumo.reload();

should give access to the select box, but the .SlectBox css class is not added to the node.

**Comment by HemantNegi** [comment]
Im unable to understand what u want. please can you explain.

**Comment by thoka** [comment]
I was simply not finding the select box using $('select.SlectBox') as I found in the docs.

But for me it doesnt matter any more. I was trying to use sumoselect for multiselect boxes in the iD openstreetmap editor. But I switched to implement it directly in D3. 

Thank you for taking care.
