### ISSUE TITLE
Placeholder doesn't work.

### ISSUE THREAD

**Issue by CSergienko** [HemantNegi/jquery.sumoselect#61]
Using 2.1.0. Placeholders aren't working at all.

```
$('.selectbox').SumoSelect({
     placeholder: 'Test Placeholder'
});
```

Is this not the correct way?

**Comment by HemantNegi** [comment]
Hi,

Please check the demo page http://hemantnegi.github.io/jquery.sumoselect/sumoselect_demo.html
its working there, The recommended way is to set placeholder="Placeholder" attribute on select.

Hope it helps
cheers!

**Comment by CSergienko** [comment]
That's very peculiar, because I did that too. It just ignores the placeholder.

`<select id="id_helpwithbill" name="helpwithbill" class="selectbox" placeholder="Test">` does nothing, it still shows the first `<option>`

**Comment by HemantNegi** [comment]
can you set up a fiddle which replicates your issue, so that i can inspect.

**Comment by richy2509** [comment]
I have the same issue.
When you set your SumoSelect to "multiple", the placeholder seems to work properly.
Otherwise, when your sumoSelect has been set to "single", the placeholder doesn't seem to work.

**Comment by HemantNegi** [comment]
closing this for now, you can reopen any time

**Comment by CSergienko** [comment]
Here's the fiddle, sorry for the delay. https://jsfiddle.net/twjzyqhL/

It's unstyled, but there's definitely no placeholder in there.
