### ISSUE TITLE
Sumoselect  working slow in IE11

### ISSUE THREAD

**Issue by himmatdb** [HemantNegi/jquery.sumoselect#62]
Sumoselect (multiselect) working fine in all browsers except IE11. Even it works fine in IE9 and IE10. There are 4,000 entries in multiselect. Why it is working slow in ie11? any solution?

**Comment by HemantNegi** [comment]
I can't understand the problem, for me its working fine on windows 8.1 ie 11.
must be an issue with browser configurations
read this thread https://social.msdn.microsoft.com/Forums/ie/en-US/ac772d61-455f-40db-8b8c-42686e0eb21e/windows-81-and-ie-11-slow-slow-slow?forum=iewebdevelopment

**Comment by Johnb21** [comment]
I am also having a problem with large drop down options. I ran a profile using chrome and found Sumo Select is apparently running appendChild for each item in the drop down opposed to dumping the entire list all at once. This causes a massive javascript memory load when writing appending each individually.

Bootstrap Multiselect does not have this issue when using the same number of items.

**Comment by HemantNegi** [comment]
So you suggest if we add the entire list in one go, It will increase performance.

**Comment by Mo700** [comment]
Why is this closed? Is there a solution?
