### ISSUE TITLE
sumo.unSelectItem is not working

### ISSUE THREAD

**Issue by rachnagupta1** [HemantNegi/jquery.sumoselect#63]
I am trying to unslelect particular item but it is not working.
like - $('#parameter')[0].sumo.unSelectItem(3);		
while its working fine with 0 index

**Comment by HemantNegi** [comment]
can you provide more details, mostly the html for your select element.
it may be possible that there may present duplicate values in options.

or best if you can replicate issue on a fiddle.

Thanks

**Comment by HemantNegi** [comment]
closing this for now, you can reopen any time
