### ISSUE TITLE
Optgroups not working

### ISSUE THREAD

**Issue by jpike88** [HemantNegi/jquery.sumoselect#65]
No errors, just doesn't work.

![screen shot 2015-05-23 at 9 41 25 pm](https://cloud.githubusercontent.com/assets/9585787/7783855/7c6a0678-0194-11e5-9ca4-6472260e0216.png)

**Comment by jpike88** [comment]
Odd behaviour, just doesn't seem to like groups at all.

![screen shot 2015-05-23 at 9 42 16 pm](https://cloud.githubusercontent.com/assets/9585787/7783857/9c809d96-0194-11e5-9622-7da9969abb71.png)

**Comment by HemantNegi** [comment]
please check https://github.com/HemantNegi/jquery.sumoselect/issues/59
