### ISSUE TITLE
Getting somoselect to fire when a checkbox is checked or unchecked

### ISSUE THREAD

**Issue by Shadow-Lord** [HemantNegi/jquery.sumoselect#66]
Hi,

When a checkbox is checked or unchecked how do I get it to fire an event.
http://jsfiddle.net/p89ka9jq/22/

Thanks

**Comment by HemantNegi** [comment]
there you go http://jsfiddle.net/p89ka9jq/23/

**Comment by Shadow-Lord** [comment]
Hi,

I'm trying to get it to work the same as this:

http://jsfiddle.net/3jr2v/705/

**Comment by HemantNegi** [comment]
Hi,

There is no proper way in native select element to get the changed option of a multiple select. unfortunately this is also not handled in sumoselect (will try to implement in next release).

however for now you can achieve the similar behaviour as http://jsfiddle.net/p89ka9jq/36/

Regards
