### ISSUE TITLE
Placeholder to only show when dropdown is disabled

### ISSUE THREAD

**Issue by Shadow-Lord** [HemantNegi/jquery.sumoselect#68]
Hi,

When I set jQuery("#test")[0].sumo.disable(); I want only the Placeholder then to display 'Please Select a County First'.

At the moment I have $("#test").SumoSelect({ placeholder: 'Please Select a County First'}); , but that placeholder is also shown if no checkboxes are ticked.

Thanks

**Comment by HemantNegi** [comment]
Hi,
I unable to understand what you are trying to achieve.
you can always customise the appearance by overriding sumoselect.css

Regards

**Comment by HemantNegi** [comment]
Closing this for now
