### ISSUE TITLE
Impossible to select dynamically added element lists

### ISSUE THREAD

**Issue by nikto1** [HemantNegi/jquery.sumoselect#69]
I was trying to add dynamically some li elements in the  `$( '.optWrapper .options ')`  via json, but after i added the elements i cannot select the added elements.

Code:
```javascript
function ricreate_dep(){
	$.getJSON('index.php?dispatch=chat/ricreate_departments',function(json){ 
        $.each(json, function(key, val) {
	$('#group_id').append('<option value='+ val.id +'>'+ val.name +'</option>');
	$('.optWrapper .options').append("<li data-val=" + val.id + "><span><i></i></span><label>" + val.name + "</label></li>");
        }) 
        });
}
```

I cannot use `$('select.SlectBox')[0].sumo.add('india'); ` because the SumoSelect is initialized from another function which creates dynamically a td row.
This function is called inside an ajax call.
Hope it's clear, because it's a bit complicated :-))
So is it possibile to delegate the click events instead of direct clicking the "checkboxes" (`<i></i>`) ?

Thanks in advance

**Comment by nikto1** [comment]
Problem solved by rewirting some lines of code. Thanks anyway!

**Comment by AbhilashGeorge** [comment]
i am facing the same issue i cannot select checkboxes after i dynamically created it from ajax. can youhelp me

**Comment by nikto1** [comment]
@AbhilashGeorge after you append your dynamic option to your select box (e.g. "`#your-selector`"), you need to attack it also to the sumoselect like.
` $('#your-selector')[0].sumo.add(val.id,val.name);`
This is how i solved it. Hard to tell you more without seeing your piece of code.
Regards
