### ISSUE TITLE
sumoselect methods does not work on ipad (IOS 6.0)

### ISSUE THREAD

**Issue by jensing** [HemantNegi/jquery.sumoselect#7]
Hi,

i have tested the Sumoselect methods like add, unselect item etc.. with an Ipad (Version 6). All the methods doesn't work. 
The Problems i.e.: if you unselect an item with $("#test")[0].sumo.unSelectItem(0), the first item in the original select option is unselected correctly, but the Sumoselelect itself does not change. The item is still marked as selected. Sumoselect does not update its state.

Another problem: You cannot loop through items i.e: 
 $("#" + id + " option").each(function(i) {

$("#" + id)[0].sumo.unSelectItem(i);

```
    });
```

All these problems seems to be a I-Pad specific. I tested this issues with Safari Browser on my window machine. Everything works. Also with Chrome, Firefox and IE no problems.

Well. Next week I have to finish a bigger project and your sumoselect is a important part of it. Do you have planned your next release already?  

It would be very nice, if you can check this issues & and the Issue I wrote you some days before.

Thanks for your answer
Jens

**Comment by OmarSaaPe** [comment]
That works for me
`
//For the plugin view

$('#IdSelectInputSumo').closest('div.SumoSelect').find('li').each(function(){
                    if($(this).hasClass('selected')){
                        $(this).removeClass('selected');
                    }
                });
//For the plugin functionality
$('#IdSelectInputSumo')[0].sumo.unSelectAll();
`

**Comment by crochelt** [comment]
This works on mobile browsers if you use multiple Sumoselectboxes:

var numSelectboxes = $('.SelectClass').length; 
for (var j = 0; j < numSelectboxes; j++) {					
         var numOptions = $('.SelectClass')[j].options.length; 
        //Unselect all options of each select box
        for (var k = 0; k < numOptions; k++) {
	        $('.SelectClass')[j].sumo.unSelectItem(k);
	}
}

**Comment by vanboom** [comment]
Suggest reopening this...
unSelectAll()  and selectAll() methods do not work on mobile devices, I have isolated some code around line 662 of jquery.sumoselect.js and will submit PR if I can solve it.
