### ISSUE TITLE
Trigger change event on selectItem or unSelectItem

### ISSUE THREAD

**Issue by HemantNegi** [HemantNegi/jquery.sumoselect#70]

**Comment by pangolingo** [comment]
Related to this: Calling selectItem and unselectItem do not update the state of the "Select All" checkbox. For instance, if there are no items selected , the Select All checkbox will be white/empty. Running this JS `$('.select1')[0].sumo.selectItem(4)` will select the proper item, but the Select All checkbox remains white. I expect it to turn gray, which is the standard appearance when one item is selected.

This can be resolved by adding `O.selAllState()` to the `toggSel` method. This may also apply to `toggDis`–I haven't tested the disabling functionality.
