### ISSUE TITLE
Search is required in sumo select

### ISSUE THREAD

**Issue by sadashivm** [HemantNegi/jquery.sumoselect#72]
Hi Hemant u did awesome sumo select jquery plgin ,i'm using in my project and one more thing  i request to you that  there is no search option in dropdown. if i want to search an item how i will do it.

willl you do it

**Comment by mgibbs189** [comment]
:+1: A search box would really help with finding the <option> within long lists.

Maybe it's worth borrowing the functionality from Select2, e.g.

![select2](http://i.imgur.com/1fTfVZ3.png)

**Comment by samcov** [comment]
I agree, it's very unproductive attempting to find things in a long list! Even the ancient select would get you in the ballpark if you hit a letter on the keyboard, so I totally agree that this is needed.

IMO, a very simple implementation would suffice!

**Comment by jpike88** [comment]
this is really needed.

**Comment by electricneuron** [comment]
Agreed. It's beautiful. Just the search is pending.

**Comment by paerhaty** [comment]
+1

**Comment by HemantNegi** [comment]
Thanks for all your inputs, i will do it in next release soon.

Thanks!

**Comment by samcov** [comment]
Thanks Hemant.

**Comment by te-deum** [comment]
Let see my pull request. I add a filtering input text when you activate select all option.
https://github.com/HemantNegi/jquery.sumoselect/pull/88

Hope you will find this usefull.

**Comment by george1974** [comment]
Looking forward to the autocomplete feature in the next release. Otherwise this solves 90% of my problem.Keep up the good work.

**Comment by samcov** [comment]
Is there an estimate on the arrival of the next version?

**Comment by HemantNegi** [comment]
Hi every one here,

I have pushed a working draft of search in master branch.
can u please test it on your end.
Thanks

**Comment by samcov** [comment]
It appears to be working, simply add "search: true". 

However, I'm not sure what the search text is for, I never see it.

**Comment by HemantNegi** [comment]
`searchText ` is the placeholder for search textbox
