### ISSUE TITLE
Clicking vertical scrollbar in dropdown using IE closes menu 

### ISSUE THREAD

**Issue by lambert-velir** [HemantNegi/jquery.sumoselect#74]
Try this in IE11: http://codepen.io/lambert-velir/pen/JdJRmx

Open the menu and click on the scroll bar. The menu should stay open, but the blur is wrongfully being fired and closing the dropdown. This seems to be an issue with IE that needs to be hacked around:

https://github.com/twitter/typeahead.js/issues/705
https://github.com/brianreavis/selectize.js/issues/182

Is there a fix for this?

**Comment by HemantNegi** [comment]
I think this must have been fixed as sumoselect no longer depends on blur for closing.
