### ISSUE TITLE
Adding methods

### ISSUE THREAD

**Issue by wickedRidge** [HemantNegi/jquery.sumoselect#75]
Hi, thanks for making such an awesome plugin.  I don't usually have to modify plugins but the project I am working on requires some custom functionality.  Could you tell me how to add method/functions while keeping the same way of invoking them (i.e. $('#selector)[0].sumo.selectAll())? I could find any specifics about how to extend functionality of things that already extend JQuery. Thanks.

**Comment by HemantNegi** [comment]
You can add them any where in between as like selectAll() method. they all will be accessible like any methods.
