### ISSUE TITLE
Sumo Select selection not working in IE11

### ISSUE THREAD

**Issue by MS-2610** [HemantNegi/jquery.sumoselect#76]
When I click on any option in multi-select list , It does not get selected , seems like it is read only in IE . this works fine in chrome and fire fox.

Also , there are no errors in console log.

Is there anything I can do to fix this issue ?

**Comment by hardeverick** [comment]
I have the same issue currently. It doesn't seem to have happen consistently, but it is happening to a lot of people.

**Comment by HemantNegi** [comment]
Please can you guys try to look into this issue. as i don't have a windows system

**Comment by deepaksri81** [comment]
I had the same issue but I found that the Document mode was set to IE7. Please check by F12 and go to Emulation tab and change to Edge.

**Comment by HemantNegi** [comment]
Can you inspect the element structure, there can be some css glitch preventing the click on option.

**Comment by hardev** [comment]
In my case it is on Edge not IE7

**Comment by hardeverick** [comment]
In my case it is on Edge not IE7

**Comment by djros** [comment]
When I click on any option in multi-select list , it does not get selected in IE11 at clients side. 
It does not work on Firefox either. However the same code works fine @  IE and Firefox  in my browser.

There are no errors in console log.

Is there anything I need to install or can do to fix this issue ? 

Version use: jquery.sumoselect - v2.1.0

Thanking u in advance.

**Comment by HemantNegi** [comment]
Please reopen if issue still persist.
