### ISSUE TITLE
backstretch image flashes when closing multiselect

### ISSUE THREAD

**Issue by designerken** [HemantNegi/jquery.sumoselect#80]
I have a site using your plug-in and seems when I close the dropdown by clicking off of it, the image in my background (loaded by Backstretch) flashes.

Have you experienced that before?
Here is a temporary link to the page in action: http://urlgone.com/0c2d20/

**Comment by HemantNegi** [comment]
Thats weird, no that never happened to me.
from what i suspect you have that background image in a <img> tag positioned absolute.
try to apply that image by setting it as `background-image` .

This will do the fix for you, meanwhile i will further investigate this.

**Comment by designerken** [comment]
I am using the backstretch js (https://github.com/srobbin/jquery-backstretch) to accomplish that loading of image. I'd rather not change the CSS from default. I know that is not ideal but I will live with the flashing for now. Let me know if you find something. Thanks
