### ISSUE TITLE
Object doesn't support property or method 'indexOf'

### ISSUE THREAD

**Issue by bandersen15** [HemantNegi/jquery.sumoselect#82]
SharePoint 2010 doc mode 8, IE11, jQuery 1.8.3, jQuery UI 1.9.2. 

Using multiple selection mode, the combination of unchecking a selected item and checking an unselected item produces the error: SCRIPT438: Object doesn't support property or method 'indexOf'
jquery.sumoselect.js, Line: 163, Column: 37

Error does not occur if "okCancelInMulti" and "triggerChangeCombined" parameters are FALSE.

Thanks for your time and service.

**Comment by HemantNegi** [comment]
unable to replicate.
