### ISSUE TITLE
Item Filter

### ISSUE THREAD

**Issue by Aidurber** [HemantNegi/jquery.sumoselect#83]
This is an enhancement suggestion, I think it would round off an already great plugin if it supported filtering. 

If it was possible to filter by: value; name; both value and name; and group, then I think you would have an incredibly powerful select tool.

**Comment by te-deum** [comment]
Let see my pull request https://github.com/HemantNegi/jquery.sumoselect/pull/88. I add a filtering input text when you activate select all option.
It will not filter element on values but on texts.

Hope you will find this usefull.

**Comment by HemantNegi** [comment]
It will be there in next release

**Comment by vidyas123** [comment]
i want to use sumoselect in gridview header filtering..it is not working in gridview and there is no selected index changed event in sumoselect...
Help me !!
