### ISSUE TITLE
Auto complete for keyboard input

### ISSUE THREAD

**Issue by italomaia** [HemantNegi/jquery.sumoselect#9]
It would be nice if it was possible to search the widget while typing.

**Comment by noface69** [comment]
This feature is the only one missing from otherwise totally perfect and useful plugin.

**Comment by HemantNegi** [comment]
will work on it soon!!

**Comment by goehimani** [comment]
if the list contains sorted data then it will be much easier for the user to find something. Let me know if sorting is already there and I am missing that..

**Comment by HemantNegi** [comment]
No its not there,
But i think you can prefill the select in sorted order in the first place.
