### ISSUE TITLE
Keep high z-index when closing "optWrapper"

### ISSUE THREAD

**Issue by bjarnef** [HemantNegi/jquery.sumoselect#90]
When the ```.optWrapper``` is open is has a z-index on 1000, but when it is closed the z-index is set to -100.

In my case I have the dropdown placed above some images and when the dropdown is open the cover a part of the images, but because of the transition and while it fade out, the options are is behind the images at the moment "open" class is removed, while I still see the animation between the images and above the images.

So when it is closed it should keep a high z-index or wait to change the z-index until the transition has ended.

This addition in my own css fix it for now:
```
.SumoSelect>.optWrapper { z-index: 1000; }
```

**Comment by HemantNegi** [comment]
will be fixed in next release
