### ISSUE TITLE
Hidden sumoselect behind div scroll

### ISSUE THREAD

**Issue by devdevmarie** [HemantNegi/jquery.sumoselect#92]
Hello -

I'm using a sumoselect in a div that has hidden overflow and a horizontal scrollbar.  The sumoselect drop down section is hidden behind the horizontal scroll.  I have tried to use the z-index to bring the sumoselect to the front with no luck.  Is there a way to do this so that the drop down shows above the scroll bar?  If not, can I change the sumoselect to drop-"UP" instead of drop down so that the select isn't hidden?

Thanks!

**Comment by Aristides-Zinelis** [comment]
I had the same problem but with a sumo at the end of the page. So I had to check the position of my sumo. hope you'll find it usefull
line 230:
showOpts: function () {
                    var O = this,
                        windowHeight = $(window).height(),
                        offset=O.E.parent().offset();
                
                    if (O.E.attr('disabled')) return; // if select is disabled then retrun
                       O.is_opened = true;
                    if(offset.top > windowHeight-205){
                        O.optDiv.addClass('open-up');
                    }else{
                        O.optDiv.addClass('open');
                     }
                    // hide options on click outside.
                    $(document).on('click.sumo', function (e) {
                            if (!O.select.is(e.target)                  // if the target of the click isn't the container...
                                && O.select.has(e.target).length === 0){ // ... nor a descendant of the container
//                               if (O.is_multi && settings.okCancelInMulti)
//                                    O._cnbtn();
//                                    O.hideOpts();
						if(!O.is_opened)return;
								O.hideOpts();
						if (O.is_multi && settings.okCancelInMulti)O._cnbtn();
                            }
                    });
you also have to add this classes:

.SumoSelect > .optWrapper {
  transition: opacity 0ms ease-out 0s, top 0ms ease-out 0s, visibility 200ms ease-out 0s;
  z-index: 100;
}

.SumoSelect > .optWrapper.open-up {
  opacity: 1;
  top: -250px;
  visibility: visible;
  z-index: 100;
}

.SumoSelect > .optWrapper > .options {
  border-radius: 2px;
  display: block;
  list-style: outside none none;
  margin: 0;
  max-height: 250px;
  padding: 0;
  overflow: visible;
}

**Comment by HemantNegi** [comment]
added an `up`option in settings which will open the select upwards.
