### ISSUE TITLE
Mobile select first item

### ISSUE THREAD

**Issue by salunet** [HemantNegi/jquery.sumoselect#94]
On mobile (iphone 6) i can't select the first option. When i do that and click OK. Then when i go back the first item isn't selected anymore.

http://jsfiddle.net/04n428s2/

**Comment by nwallis** [comment]
yes - I have the same experience.  

try this page on an iPhone 6 (not sure about other iPhones)

http://www.deakin.edu.au/about-deakin/news-and-events/events

Tapping on the sumoselect to open the drop down will automagically select the first item - unbeknownst to the user, making it appear as though you can't select the first item, when in fact its already selected..

**Comment by PixelZombie** [comment]
Set `forceCustomRendering` to `true`

**Comment by NiclasLindqvist** [comment]
Hi guys! If you add an empty optgroup when on mobile, and make it disabled, it works great! I did it like this:

````
setNativeMobile: function () {
  var O = this;
  O.E.addClass('SelectClass')//.css('height', O.select.outerHeight());
  O.E.prepend('<optgroup disabled>Label</optgroup>') // <--- this
  O.mob = true;
  O.E.change(function () {
    O.setText();
  });
},
````

**Comment by illmaxon** [comment]
This issue was detected in iOS 7 the first time and Apple seems nothing to do...

**Comment by HemantNegi** [comment]
Please reopen if issue still persist.
