### ISSUE TITLE
Sumo select is taking time to load long list!

### ISSUE THREAD

**Issue by nandhakishore92** [HemantNegi/jquery.sumoselect#95]
Hi Hemant,

Thanks for such a nice plugin! 
Plugin was too good until I used it for small lists(< 50 values). But when I started using it for long lists(705 values),It is taking time(approx 5 secs).
Steps I have followed:
* I fetched data from DB.
* Appended data to an existing multiple select HTML dropdown list.
* Appended Sumoselect plugin to that HTML dropdown using the following code:
**$('.boardingSelect').SumoSelect({ okCancelInMulti: true , triggerChangeCombined: false })**
**$('select.SlectBox')[0].sumo.reload();**

Is there anything wrong in the code? or since the list is too long, will it take this time(approx 5 secs) to load?

Regards,
Kishore

**Comment by HemantNegi** [comment]
this should fix that https://github.com/HemantNegi/jquery.sumoselect/commit/9786536f3e2c6f9ecf192222ea9bcd3285d38413
