### ISSUE TITLE
V2.1.0. does not support optgroup any more (V1.2.0 did)

### ISSUE THREAD

**Issue by HolgerSchulz** [HemantNegi/jquery.sumoselect#99]
Why does V2.1.0 does not support optgoup any more?
Or is there a trick to use optgoups?

I would like to upgrade from V1.2.0 to V2.1.0.
I need optgoups for native select on android.

Thanks
          Holger

**Comment by HemantNegi** [comment]
It does support optgroup.
as default select element is used on mobile devices, it is directly depended on mobile OS.
